baseURL = 'https://torwoodbluepool.co.uk/'
locale = 'en-GB'
title = 'Torwood Blue Pool'
description = 'Investigation of a round brick lined Blue Water Pool at Torwood near Dunipace and Larbert'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
