var _____WB$wombat$assign$function_____=function(name){return (globalThis._wb_wombat && globalThis._wb_wombat.local_init && globalThis._wb_wombat.local_init(name))||globalThis[name];};if(!globalThis.__WB_pmw){globalThis.__WB_pmw=function(obj){this.__WB_source=obj;return this;}}{
let window = _____WB$wombat$assign$function_____("window");
let self = _____WB$wombat$assign$function_____("self");
let document = _____WB$wombat$assign$function_____("document");
let location = _____WB$wombat$assign$function_____("location");
let top = _____WB$wombat$assign$function_____("top");
let parent = _____WB$wombat$assign$function_____("parent");
let frames = _____WB$wombat$assign$function_____("frames");
let opener = _____WB$wombat$assign$function_____("opener");
(function(){function h(a){throw a;}
var k=void 0,l=!0,n=null,o=!1,r,t=this,aa=function(){},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},ca=function(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"string"==typeof a},da=function(a){return"function"==ba(a)},ea=function(a){var b=typeof a;return"object"==b&&a!=n||"function"==b},ha=function(a){return a[fa]||(a[fa]=++ga)},fa="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ga=0,ia=function(a,
b,c){return a.call.apply(a.bind,arguments)},ja=function(a,b,c){a||h(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},v=function(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return v.apply(n,arguments)},ka=function(a,b){var c=Array.prototype.slice.call(arguments,
1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}},x=Date.now||function(){return+new Date},y=function(a,b){var c,d=b,f=a.split(".");c=c||t;!(f[0]in c)&&c.execScript&&c.execScript("var "+f[0]);for(var e;f.length&&(e=f.shift());)!f.length&&d!==k?c[e]=d:c=c[e]?c[e]:c[e]={}},z=function(a,b){function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c};var A=document,C=window;var D=function(a){Error.captureStackTrace?Error.captureStackTrace(this,D):this.stack=Error().stack||"";a&&(this.message=""+a)};z(D,Error);D.prototype.name="CustomError";var la=function(a,b){this.width=a;this.height=b};la.prototype.O=function(){return new la(this.width,this.height)};la.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};la.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};var ma=function(a,b,c){a.addEventListener?a.addEventListener(b,c,o):a.attachEvent&&a.attachEvent("on"+b,c)},na=function(a){return!!a&&(0<a.indexOf("?google_debug")||0<a.indexOf("&google_debug"))};var E=function(){};E.prototype.Y=o;E.prototype.ea=function(){this.Y||(this.Y=l,this.d())};E.prototype.d=function(){this.fd&&oa.apply(n,this.fd);if(this.xc)for(;this.xc.length;)this.xc.shift()()};var F=function(a){a&&"function"==typeof a.ea&&a.ea()},oa=function(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ca(d)?oa.apply(n,d):F(d)}};var H=Array.prototype,pa=H.indexOf?function(a,b,c){return H.indexOf.call(a,b,c)}:function(a,b,c){c=c==n?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},qa=H.forEach?function(a,b,c){H.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=u(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},ra=H.some?function(a,b,c){return H.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=u(a)?a.split(""):a,
e=0;e<d;e++)if(e in f&&b.call(c,f[e],e,a))return l;return o},sa=function(a,b){var c=pa(a,b);if(0<=c){var d=a;H.splice.call(d,c,1)}},ta=function(a){return H.concat.apply(H,arguments)},ua=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},va=ua;var wa="StopIteration"in t?t.StopIteration:Error("StopIteration"),xa=function(){};xa.prototype.next=function(){h(wa)};xa.prototype.gd=function(){return this};var ya=function(a,b){var c,d;for(d in a)b.call(c,a[d],d,a)},za=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Ba="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ca=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Ba.length;e++)c=Ba[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Da=function(a){if("function"==typeof a.J)return a.J();if(u(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return za(a)};var I=function(a,b){this.A={};this.e=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){d=a;d instanceof I?(c=d.ha(),d=d.J()):(c=Aa(d),d=za(d));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}};r=I.prototype;r.c=0;r.Ma=0;r.J=function(){Ea(this);for(var a=[],b=0;b<this.e.length;b++){var c=this.e[b];a.push(this.A[c])}return a};r.ha=function(){Ea(this);return this.e.concat()};
r.va=function(a){return Fa(this.A,a)};r.remove=function(a){return Fa(this.A,a)?(delete this.A[a],this.c--,this.Ma++,this.e.length>2*this.c&&Ea(this),l):o};var Ea=function(a){if(a.c!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];Fa(a.A,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.c!=a.e.length){for(var f={},c=b=0;b<a.e.length;)d=a.e[b],Fa(f,d)||(a.e[c++]=d,f[d]=1),b++;a.e.length=c}};I.prototype.get=function(a,b){return Fa(this.A,a)?this.A[a]:b};
I.prototype.set=function(a,b){Fa(this.A,a)||(this.c++,this.e.push(a),this.Ma++);this.A[a]=b};I.prototype.O=function(){return new I(this)};I.prototype.gd=function(a){Ea(this);var b=0,c=this.e,d=this.A,f=this.Ma,e=this,g=new xa;g.next=function(){for(;;){f!=e.Ma&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(wa);var g=c[b++];return a?g:d[g]}};return g};var Fa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Ga,Ha,Ia,Ja,Ka,La=function(){return t.navigator?t.navigator.userAgent:n};Ka=Ja=Ia=Ha=Ga=o;var Ma;if(Ma=La()){var Na=t.navigator;Ga=0==Ma.indexOf("Opera");Ha=!Ga&&-1!=Ma.indexOf("MSIE");Ja=(Ia=!Ga&&-1!=Ma.indexOf("WebKit"))&&-1!=Ma.indexOf("Mobile");Ka=!Ga&&!Ia&&"Gecko"==Na.product}var Oa=Ga,J=Ha,K=Ka,L=Ia,Pa=Ja,Qa;
a:{var Ra="",Sa;if(Oa&&t.opera)var Ta=t.opera.version,Ra="function"==typeof Ta?Ta():Ta;else if(K?Sa=/rv\:([^\);]+)(\)|;)/:J?Sa=/MSIE\s+([^\);]+)(\)|;)/:L&&(Sa=/WebKit\/(\S+)/),Sa)var Ua=Sa.exec(La()),Ra=Ua?Ua[1]:"";if(J){var Va,Wa=t.document;Va=Wa?Wa.documentMode:k;if(Va>parseFloat(Ra)){Qa=""+Va;break a}}Qa=Ra}
var Xa=Qa,Ya={},M=function(a){var b;if(!(b=Ya[a])){b=Ya;for(var c=a,d=a,a=Xa,f=0,a=(""+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=(""+d).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(a.length,d.length),g=0;0==f&&g<e;g++){var i=a[g]||"",m=d[g]||"",j=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var s=j.exec(i)||["","",""],w=p.exec(m)||["","",""];if(0==s[0].length&&0==w[0].length)break;var f=0==s[1].length?0:parseInt(s[1],10),T=0==w[1].length?0:parseInt(w[1],10),
f=(f<T?-1:f>T?1:0)||((0==s[2].length)<(0==w[2].length)?-1:(0==s[2].length)>(0==w[2].length)?1:0)||(s[2]<w[2]?-1:s[2]>w[2]?1:0)}while(0==f)}a=f;b=b[c]=0<=a}return b},Za={},$a=function(a){return Za[a]||(Za[a]=J&&!!document.documentMode&&document.documentMode>=a)};var ab=[],bb=o;var cb=function(a){cb[" "](a);return a};cb[" "]=aa;var db=function(a,b){try{return cb(a[b]),l}catch(c){}return o};!J||$a(9);var eb=!J||$a(9),fb=J&&!M("8");!L||M("528");K&&M("1.9b")||J&&M("8")||Oa&&M("9.5")||L&&M("528");K&&!M("8")||J&&M("9");var gb=function(a,b){this.type=a;this.currentTarget=this.target=b};z(gb,E);r=gb.prototype;r.d=function(){delete this.type;delete this.target;delete this.currentTarget};r.ka=o;r.defaultPrevented=o;r.Pa=l;r.preventDefault=function(){this.defaultPrevented=l;this.Pa=o};var hb=function(a,b){a&&this.Ka(a,b)};z(hb,gb);r=hb.prototype;r.target=n;r.relatedTarget=n;r.offsetX=0;r.offsetY=0;r.clientX=0;r.clientY=0;r.screenX=0;r.screenY=0;r.button=0;r.keyCode=0;r.charCode=0;r.ctrlKey=o;r.altKey=o;r.shiftKey=o;r.metaKey=o;r.Qa=n;
r.Ka=function(a,b){var c=this.type=a.type;gb.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?K&&(db(d,"nodeName")||(d=n)):"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=L||a.offsetX!==k?a.offsetX:a.layerX;this.offsetY=L||a.offsetY!==k?a.offsetY:a.layerY;this.clientX=a.clientX!==k?a.clientX:a.pageX;this.clientY=a.clientY!==k?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=
a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.Qa=a;a.defaultPrevented&&this.preventDefault();delete this.ka};r.preventDefault=function(){hb.l.preventDefault.call(this);var a=this.Qa;if(a.preventDefault)a.preventDefault();else if(a.returnValue=o,fb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};r.qa=function(){return this.Qa};
r.d=function(){hb.l.d.call(this);this.relatedTarget=this.currentTarget=this.target=this.Qa=n};var ib=function(){},jb=0;r=ib.prototype;r.key=0;r.ia=o;r.pc=o;r.Ka=function(a,b,c,d,f,e){da(a)?this.oc=l:a&&a.handleEvent&&da(a.handleEvent)?this.oc=o:h(Error("Invalid listener argument"));this.ta=a;this.bc=b;this.src=c;this.type=d;this.capture=!!f;this.qb=e;this.pc=o;this.key=++jb;this.ia=o};r.handleEvent=function(a){return this.oc?this.ta.call(this.qb||this.src,a):this.ta.handleEvent.call(this.ta,a)};var kb={},N={},O={},lb="on",mb={},nb=function(a,b,c,d,f){if(b){if("array"==ba(b)){for(var e=0;e<b.length;e++)nb(a,b[e],c,d,f);return n}var d=!!d,g=N;b in g||(g[b]={c:0,q:0});g=g[b];d in g||(g[d]={c:0,q:0},g.c++);var g=g[d],i=ha(a),m;g.q++;if(g[i]){m=g[i];for(e=0;e<m.length;e++)if(g=m[e],g.ta==c&&g.qb==f){if(g.ia)break;return m[e].key}}else m=g[i]=[],g.c++;var j=ob,p=eb?function(a){return j.call(p.src,p.key,a)}:function(a){a=j.call(p.src,p.key,a);if(!a)return a},e=p;e.src=a;g=new ib;g.Ka(c,e,a,b,d,
f);c=g.key;e.key=c;m.push(g);kb[c]=g;O[i]||(O[i]=[]);O[i].push(g);a.addEventListener?(a==t||!a.ac)&&a.addEventListener(b,e,d):a.attachEvent(b in mb?mb[b]:mb[b]=lb+b,e);return c}h(Error("Invalid event type"))},pb=function(a,b,c,d,f){if("array"==ba(b))for(var e=0;e<b.length;e++)pb(a,b[e],c,d,f);else{d=!!d;a:{e=N;if(b in e&&(e=e[b],d in e&&(e=e[d],a=ha(a),e[a]))){a=e[a];break a}a=n}if(a)for(e=0;e<a.length;e++)if(a[e].ta==c&&a[e].capture==d&&a[e].qb==f){qb(a[e].key);break}}},qb=function(a){if(!kb[a])return o;
var b=kb[a];if(b.ia)return o;var c=b.src,d=b.type,f=b.bc,e=b.capture;c.removeEventListener?(c==t||!c.ac)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in mb?mb[d]:mb[d]=lb+d,f);c=ha(c);f=N[d][e][c];if(O[c]){var g=O[c];sa(g,b);0==g.length&&delete O[c]}b.ia=l;f.ic=l;rb(d,e,c,f);delete kb[a];return l},rb=function(a,b,c,d){if(!d.Oa&&d.ic){for(var f=0,e=0;f<d.length;f++)if(d[f].ia){var g=d[f].bc;g.src=n}else f!=e&&(d[e]=d[f]),e++;d.length=e;d.ic=o;0==e&&(delete N[a][b][c],N[a][b].c--,0==
N[a][b].c&&(delete N[a][b],N[a].c--),0==N[a].c&&delete N[a])}},tb=function(a,b,c,d,f){var e=1,b=ha(b);if(a[b]){a.q--;a=a[b];a.Oa?a.Oa++:a.Oa=1;try{for(var g=a.length,i=0;i<g;i++){var m=a[i];m&&!m.ia&&(e&=sb(m,f)!==o)}}finally{a.Oa--,rb(c,d,b,a)}}return Boolean(e)},sb=function(a,b){a.pc&&qb(a.key);return a.handleEvent(b)},ob=function(a,b){if(!kb[a])return l;var c=kb[a],d=c.type,f=N;if(!(d in f))return l;var f=f[d],e,g;if(!eb){var i;if(!(i=b))a:{var m;i="window.event";i=i.split(".");for(m=m||t;e=i.shift();)if(m[e]!=
n)m=m[e];else{i=n;break a}i=m}e=i;m=l in f;i=o in f;if(m){if(0>e.keyCode||e.returnValue!=k)return l;a:{var j=e,p=o;if(0==j.keyCode)try{j.keyCode=-1;break a}catch(s){p=l}if(p||j.returnValue==k)j.returnValue=l}}j=new hb;j.Ka(e,this);e=l;try{if(m){for(var w=[],T=j.currentTarget;T;T=T.parentNode)w.push(T);g=f[l];g.q=g.c;for(var q=w.length-1;!j.ka&&0<=q&&g.q;q--)j.currentTarget=w[q],e&=tb(g,w[q],d,l,j);if(i){g=f[o];g.q=g.c;for(q=0;!j.ka&&q<w.length&&g.q;q++)j.currentTarget=w[q],e&=tb(g,w[q],d,o,j)}}else e=
sb(c,j)}finally{w&&(w.length=0),j.ea()}return e}d=new hb(b,this);try{e=sb(c,d)}finally{d.ea()}return e};if(bb)for(var ub=0;ub<ab.length;ub++)var vb=v(ab[ub].pd,ab[ub]),ob=vb(ob);var wb=function(){};z(wb,E);r=wb.prototype;r.ac=l;r.ob=n;r.addEventListener=function(a,b,c,d){nb(this,a,b,c,d)};r.removeEventListener=function(a,b,c,d){pb(this,a,b,c,d)};
r.dispatchEvent=function(a){var b=a.type||a,c=N;if(b in c){if(u(a))a=new gb(a,this);else if(a instanceof gb)a.target=a.target||this;else{var d=a,a=new gb(b,this);Ca(a,d)}var d=1,f,c=c[b],b=l in c,e;if(b){f=[];for(e=this;e;e=e.ob)f.push(e);e=c[l];e.q=e.c;for(var g=f.length-1;!a.ka&&0<=g&&e.q;g--)a.currentTarget=f[g],d&=tb(e,f[g],a.type,l,a)&&a.Pa!=o}if(e=o in c)if(e=c[o],e.q=e.c,b)for(g=0;!a.ka&&g<f.length&&e.q;g++)a.currentTarget=f[g],d&=tb(e,f[g],a.type,o,a)&&a.Pa!=o;else for(f=this;!a.ka&&f&&e.q;f=
f.ob)a.currentTarget=f,d&=tb(e,f,a.type,o,a)&&a.Pa!=o;a=Boolean(d)}else a=l;return a};r.d=function(){wb.l.d.call(this);var a,b,c=0,d=this==n,f=a==n,e=b==n;b=!!b;if(d)ya(O,function(d){for(var g=d.length-1;0<=g;g--){var i=d[g];if((f||a==i.type)&&(e||b==i.capture))qb(i.key),c++}});else if(d=ha(this),O[d])for(var d=O[d],g=d.length-1;0<=g;g--){var i=d[g];if((f||a==i.type)&&(e||b==i.capture))qb(i.key),c++}this.ob=n};var yb=function(a,b){this.la=a||1;this.ua=b||xb;this.ub=v(this.dd,this);this.vb=x()};z(yb,wb);yb.prototype.enabled=o;var xb=t.window,zb=0.8;r=yb.prototype;r.I=n;r.dd=function(){if(this.enabled){var a=x()-this.vb;0<a&&a<this.la*zb?this.I=this.ua.setTimeout(this.ub,this.la-a):(this.dispatchEvent("tick"),this.enabled&&(this.I=this.ua.setTimeout(this.ub,this.la),this.vb=x()))}};r.start=function(){this.enabled=l;this.I||(this.I=this.ua.setTimeout(this.ub,this.la),this.vb=x())};
r.stop=function(){this.enabled=o;this.I&&(this.ua.clearTimeout(this.I),this.I=n)};r.d=function(){yb.l.d.call(this);this.stop();delete this.ua};var Ab=function(a,b){var c;da(a)?c&&(a=v(a,c)):a&&"function"==typeof a.handleEvent?a=v(a.handleEvent,a):h(Error("Invalid listener argument"));return 2147483647<b?-1:xb.setTimeout(a,b||0)};var Bb=function(a,b,c){this.rb=a;this.la=b||0;this.za=c;this.ad=v(this.ed,this)};z(Bb,E);r=Bb.prototype;r.ma=0;r.d=function(){Bb.l.d.call(this);this.stop();delete this.rb;delete this.za};r.start=function(a){this.stop();this.ma=Ab(this.ad,a!==k?a:this.la)};r.stop=function(){0!=this.ma&&xb.clearTimeout(this.ma);this.ma=0};r.ed=function(){this.ma=0;this.rb&&this.rb.call(this.za)};var P=function(a,b){this.x=a!==k?a:0;this.y=b!==k?b:0};P.prototype.O=function(){return new P(this.x,this.y)};var Cb;!J||$a(9);!K&&!J||J&&$a(9)||K&&M("1.9.1");J&&M("9");var Q=function(a){return a?new Db(Eb(a)):Cb||(Cb=new Db)},Fb=function(a){a=a.document;a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new la(a.clientWidth,a.clientHeight)},Gb=function(a,b){a.appendChild(b)},Hb=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},Ib=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},Eb=
function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},Db=function(a){this.ba=a||t.document||document};Db.prototype.createElement=function(a){return this.ba.createElement(a)};Db.prototype.b=function(){return this.ba.parentWindow||this.ba.defaultView};var Jb=function(a){var b=a.ba,a=!L&&"CSS1Compat"==b.compatMode?b.documentElement:b.body,b=b.parentWindow||b.defaultView;return a=new P(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)};Db.prototype.appendChild=Gb;
Db.prototype.contains=Ib;var Kb=function(a){this.za=a;this.e=[]};z(Kb,E);var Lb=[];Kb.prototype.d=function(){Kb.l.d.call(this);qa(this.e,qb);this.e.length=0};Kb.prototype.handleEvent=function(){h(Error("EventHandler.handleEvent not implemented"))};var Mb=function(a){if(/^\s*$/.test(a))return o;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,f=/^[\],:{}\s\u2028\u2029]*$/;return f.test(a.replace(b,"@").replace(c,"]").replace(d,""))},Nb=function(a){a=""+a;if(Mb(a))try{return eval("("+a+")")}catch(b){}h(Error("Invalid JSON string: "+a))},Qb=function(a){var b;b=new Ob(b);var c=[];Pb(b,a,c);return a=c.join("")},Ob=function(a){this.Sa=
a},Pb=function(a,b,c){switch(typeof b){case "string":Rb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==n){c.push("null");break}if("array"==ba(b)){var d=a,a=b,b=a.length;c.push("[");for(var f="",e=0;e<b;e++)c.push(f),f=a[e],Pb(d,d.Sa?d.Sa.call(a,""+e,f):f,c),f=",";c.push("]");break}c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),
Rb(d,c),c.push(":"),Pb(a,a.Sa?a.Sa.call(b,d,f):f,c),e=","));c.push("}");break;case "function":break;default:h(Error("Unknown type: "+typeof b))}},Sb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Tb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,Rb=function(a,b){b.push('"',a.replace(Tb,function(a){if(a in Sb)return Sb[a];var b=a.charCodeAt(0),f="\\u";16>b?f+="000":256>b?f+="00":4096>b&&(f+="0");return Sb[a]=
f+b.toString(16)}),'"')};var Ub=function(){this.Ca={}};z(Ub,E);Ub.prototype.r=function(a){a&&a()};Ub.prototype.k=function(){return l};var Vb=function(a,b){var c,d="expandable_ad";a.Ca[d]={B:b,Ub:!!c}},Wb=function(a,b){if(b&&u(a))try{return Nb(a)}catch(c){return n}else if(!b&&!u(a))return Qb(a);return a};Ub.prototype.d=function(){Ub.l.d.call(this);F(this.Uc);delete this.Uc;delete this.Ca;delete this.Kb};var Xb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Zb=function(a){if(Yb){Yb=o;var b=t.location;if(b){var c=b.href;if(c){var d=3;if((c=(c=Zb(c)[d]||n)&&decodeURIComponent(c))&&c!=b.hostname)Yb=l,h(Error())}}}return a.match(Xb)},Yb=L,$b=function(a){var b=Zb(a),c,a=b[1],d=b[2],f=b[3],b=b[4],e,g,i=[];a&&i.push(a,":");f&&(i.push("//"),d&&i.push(d,"@"),i.push(f),b&&i.push(":",b));c&&i.push(c);e&&i.push("?",e);g&&i.push("#",
g);return c=i.join("")};var R=function(a,b){var c;if(a instanceof R)this.o=b!==k?b:a.o,ac(this,a.G),c=a.V,S(this),this.V=c,c=a.w,S(this),this.w=c,bc(this,a.P),c=a.z,S(this),this.z=c,cc(this,a.n.O()),c=a.U,S(this),this.U=c;else if(a&&(c=Zb(""+a))){this.o=!!b;ac(this,c[1]||"",l);var d=c[2]||"";S(this);this.V=d?decodeURIComponent(d):"";d=c[3]||"";S(this);this.w=d?decodeURIComponent(d):"";bc(this,c[4]);d=c[5]||"";S(this);this.z=d?decodeURIComponent(d):"";cc(this,c[6]||"",l);c=c[7]||"";S(this);this.U=c?decodeURIComponent(c):
""}else this.o=!!b,this.n=new dc(n,0,this.o)};r=R.prototype;r.G="";r.V="";r.w="";r.P=n;r.z="";r.U="";r.jd=o;r.o=o;r.toString=function(){var a=[],b=this.G;b&&a.push(ec(b,fc),":");if(b=this.w){a.push("//");var c=this.V;c&&a.push(ec(c,fc),"@");a.push(encodeURIComponent(""+b));b=this.P;b!=n&&a.push(":",""+b)}if(b=this.z)this.w&&"/"!=b.charAt(0)&&a.push("/"),a.push(ec(b,"/"==b.charAt(0)?gc:hc));(b=this.n.toString())&&a.push("?",b);(b=this.U)&&a.push("#",ec(b,ic));return a.join("")};r.O=function(){return new R(this)};
var ac=function(a,b,c){S(a);a.G=c?b?decodeURIComponent(b):"":b;a.G&&(a.G=a.G.replace(/:$/,""))},bc=function(a,b){S(a);b?(b=Number(b),(isNaN(b)||0>b)&&h(Error("Bad port number "+b)),a.P=b):a.P=n},cc=function(a,b,c){S(a);b instanceof dc?(a.n=b,a.n.wb(a.o)):(c||(b=ec(b,jc)),a.n=new dc(b,0,a.o))},S=function(a){a.jd&&h(Error("Tried to modify a read-only Uri"))};R.prototype.wb=function(a){this.o=a;this.n&&this.n.wb(a);return this};
var kc=function(a){var b;return a instanceof R?a.O():new R(a,b)},ec=function(a,b){return u(a)?encodeURI(a).replace(b,lc):n},lc=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},fc=/[#\/\?@]/g,hc=/[\#\?:]/g,gc=/[\#\?]/g,jc=/[\#\?@]/g,ic=/#/g,dc=function(a,b,c){this.p=a||n;this.o=!!c},nc=function(a){if(!a.f&&(a.f=new I,a.c=0,a.p))for(var b=a.p.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),f=n,e=n;0<=d?(f=b[c].substring(0,d),e=b[c].substring(d+1)):f=b[c];f=
decodeURIComponent(f.replace(/\+/g," "));f=mc(a,f);a.add(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}};r=dc.prototype;r.f=n;r.c=n;r.add=function(a,b){nc(this);this.p=n;var a=mc(this,a),c=this.f.get(a);c||this.f.set(a,c=[]);c.push(b);this.c++;return this};r.remove=function(a){nc(this);a=mc(this,a);return this.f.va(a)?(this.p=n,this.c-=this.f.get(a).length,this.f.remove(a)):o};r.va=function(a){nc(this);a=mc(this,a);return this.f.va(a)};
r.ha=function(){nc(this);for(var a=this.f.J(),b=this.f.ha(),c=[],d=0;d<b.length;d++)for(var f=a[d],e=0;e<f.length;e++)c.push(b[d]);return c};r.J=function(a){nc(this);var b=[];if(a)this.va(a)&&(b=ta(b,this.f.get(mc(this,a))));else for(var a=this.f.J(),c=0;c<a.length;c++)b=ta(b,a[c]);return b};r.set=function(a,b){nc(this);this.p=n;a=mc(this,a);this.va(a)&&(this.c-=this.f.get(a).length);this.f.set(a,[b]);this.c++;return this};r.get=function(a,b){var c=a?this.J(a):[];return 0<c.length?c[0]:b};
r.toString=function(){if(this.p)return this.p;if(!this.f)return"";for(var a=[],b=this.f.ha(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(""+d),d=this.J(d),e=0;e<d.length;e++){var g=f;""!==d[e]&&(g+="="+encodeURIComponent(""+d[e]));a.push(g)}return this.p=a.join("&")};r.O=function(){var a=new dc;a.p=this.p;this.f&&(a.f=this.f.O());return a};var mc=function(a,b){var c=""+b;a.o&&(c=c.toLowerCase());return c};
dc.prototype.wb=function(a){var b=a&&!this.o;if(b){nc(this);this.p=n;var c=this.f,b=function(a,b){var c=b.toLowerCase();if(b!=c){this.remove(b);var d=a;this.remove(c);0<d.length&&(this.p=n,this.f.set(mc(this,c),va(d)),this.c+=d.length)}};if("function"==typeof c.forEach)c.forEach(b,this);else if(ca(c)||u(c))qa(c,b,this);else{var d;var f=c;if("function"==typeof f.ha)d=f.ha();else if("function"!=typeof f.J)if(ca(f)||u(f)){d=[];for(var f=f.length,e=0;e<f;e++)d.push(e)}else d=Aa(f);else d=k;c=Da(c);f=
c.length;for(e=0;e<f;e++)b.call(this,c[e],d&&d[e])}}this.o=a};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var U=function(a,b){this.La=[];this.hc=a;this.Zb=b||n};r=U.prototype;r.v=o;r.xa=o;r.ya=0;r.tb=o;r.Rc=o;r.Ja=0;r.cancel=function(a){if(this.v)this.wa instanceof U&&this.wa.cancel();else{if(this.ja){var b=this.ja;delete this.ja;a?b.cancel(a):(a=b,a.Ja--,0>=a.Ja&&a.cancel())}this.hc?this.hc.call(this.Zb,this):this.tb=l;this.v||this.fc(new oc)}};r.dc=function(a,b){pc(this,a,b);this.ya--;0==this.ya&&this.v&&qc(this)};
var pc=function(a,b,c){a.v=l;a.wa=c;a.xa=!b;qc(a)},sc=function(a){a.v&&(a.tb||h(new rc),a.tb=o)};U.prototype.B=function(a){sc(this);pc(this,l,a)};U.prototype.fc=function(a){sc(this);pc(this,o,a)};var tc=function(a,b,c,d){a.La.push([b,c,d]);a.v&&qc(a)},uc=function(a,b){var c=v(b.hd,b);tc(a,c,n,k)};U.prototype.hd=function(a){var b=new U;tc(this,b.B,b.fc,b);a&&(b.ja=this,this.Ja++);return b};
var vc=function(a){return ra(a.La,function(a){return da(a[1])})},qc=function(a){a.sb&&(a.v&&vc(a))&&(t.clearTimeout(a.sb),delete a.sb);a.ja&&(a.ja.Ja--,delete a.ja);for(var b=a.wa,c=o,d=o;a.La.length&&0==a.ya;){var f=a.La.shift(),e=f[0],g=f[1],f=f[2];if(e=a.xa?g:e)try{var i=e.call(f||a.Zb,b);i!==k&&(a.xa=a.xa&&(i==b||i instanceof Error),a.wa=b=i);b instanceof U&&(d=l,a.ya++)}catch(m){b=m,a.xa=l,vc(a)||(c=l)}}a.wa=b;d&&a.ya&&(tc(b,v(a.dc,a,l),v(a.dc,a,o)),b.Rc=l);c&&(a.sb=t.setTimeout(function(){h(new wc(b))},
0))},rc=function(){D.call(this)};z(rc,D);rc.prototype.message="Already called";var oc=function(){D.call(this)};z(oc,D);oc.prototype.message="Deferred was cancelled";var wc=function(a){D.call(this);this.message="Unhandled Error in Deferred: "+(a.message||"[No message]")};z(wc,D);var xc=["pu","lru","pru","lpu","ppu"],V={},zc=function(){var a,b=10;a=a||yc;for(var c=a.length,d="";0<b--;)d+=a.charAt(Math.floor(Math.random()*c));return d},yc="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var W=function(a){this.i=a||Q()};z(W,E);W.prototype.X=0;W.prototype.b=function(){return this.i.b()};var Ac=function(a,b){this.i=b||Q();this.a=a;this.pa=[];this.Dc=v(this.Oc,this)};z(Ac,W);r=Ac.prototype;r.X=2;r.fb=o;r.I=0;r.r=function(){0==X(this.a)?(this.H=this.a.$,this.H.XPC_toOuter=v(this.Mb,this)):this.Lb()};
r.Lb=function(){var a=l;try{if(this.H||(this.H=this.b().frameElement),this.H&&this.H.XPC_toOuter)this.$a=this.H.XPC_toOuter,this.H.XPC_toOuter.XPC_toInner=v(this.Mb,this),a=o,this.send("tp","SETUP_ACK"),this.a.F()}catch(b){}a&&(this.Qb||(this.Qb=v(this.Lb,this)),this.b().setTimeout(this.Qb,100))};r.jb=function(a){0==X(this.a)&&!this.a.k()&&"SETUP_ACK"==a?(this.$a=this.H.XPC_toOuter.XPC_toInner,this.a.F()):h(Error("Got unexpected transport message."))};
r.Mb=function(a,b){!this.fb&&0==this.pa.length?this.a.C(a,b):(this.pa.push({Fc:a,ab:b}),1==this.pa.length&&(this.I=this.b().setTimeout(this.Dc,1)))};r.Oc=function(){for(;this.pa.length;){var a=this.pa.shift();this.a.C(a.Fc,a.ab)}};r.send=function(a,b){this.fb=l;this.$a(a,b);this.fb=o};r.d=function(){Ac.l.d.call(this);this.H=this.$a=n};var Y=function(a,b){this.i=b||Q();this.a=a;this.oa=this.a.h.ppu;this.Lc=this.a.h.lpu;this.Ia=[]},Bc,Cc;z(Y,W);r=Y.prototype;r.Ac=5;r.X=4;r.mb=0;r.fa=o;r.S=o;r.Ib=n;var Dc=function(a){return"googlexpc_"+a.a.name+"_msg"},Ec=function(a){return"googlexpc_"+a.a.name+"_ack"},Gc=function(a){try{if(!a.Y&&Fc(a.a))return a.a.D.frames||{}}catch(b){}return{}};
Y.prototype.r=function(){if(!this.Y&&Fc(this.a)){if(!this.S){var a=Dc(this);this.da=Hc(this,a);this.Xa=this.b().frames[a];a=Ec(this);this.ca=Hc(this,a);this.Wa=this.b().frames[a];this.S=l}if(!Ic(this,Dc(this))||!Ic(this,Ec(this))){if(1==X(this.a))this.Ib||0<this.Ac--||(this.a.name=zc(),Jc(this),this.S=o,this.Ib=Hc(this,"googlexpc_reconnect_"+this.a.name));else if(0==X(this.a))for(var a=Gc(this),b=a.length,c=0;c<b;c++){var d;try{a[c]&&a[c].name&&(d=a[c].name)}catch(f){}if(d){var e=d.split("_");if(3==
e.length&&"googlexpc"==e[0]&&"reconnect"==e[1]){this.a.name=e[2];Jc(this);this.S=o;break}}}this.b().setTimeout(v(this.r,this),100)}else this.Eb=new Kc(this,Gc(this)[Dc(this)],v(this.Cc,this)),this.Db=new Kc(this,Gc(this)[Ec(this)],v(this.Bc,this)),this.Gb()}};
var Hc=function(a,b){var c;c="iframe";c=document.createElement(c);var d=c.style;d.position="absolute";d.top="-10px";d.left="10px";d.width="1px";d.height="1px";c.id=c.name=b;c.src=a.oa+"#INITIAL";a.b().document.body.appendChild(c);return c},Jc=function(a){a.da&&(a.da.parentNode.removeChild(a.da),a.da=n,a.Xa=n);a.ca&&(a.ca.parentNode.removeChild(a.ca),a.ca=n,a.Wa=n)},Ic=function(a,b){try{var c=Gc(a)[b];if(!c||0!=c.location.href.indexOf(a.Lc))return o}catch(d){return o}return l};
Y.prototype.Gb=function(){var a=Gc(this);!a[Ec(this)]||!a[Dc(this)]?(this.cc||(this.cc=v(this.Gb,this)),this.b().setTimeout(this.cc,100)):(this.$b=new Lc(this.oa,this.Xa),this.Fa=new Lc(this.oa,this.Wa),this.b().setTimeout(v(function(){this.$b.send("SETUP");this.fa=l},this),100))};var Mc=function(a){if(a.Pb&&a.Gc&&(a.a.F(),a.sa)){for(var b=0,c;b<a.sa.length;b++)c=a.sa[b],a.a.C(c.Kc,c.ab);delete a.sa}};
Y.prototype.Cc=function(a){if("SETUP"==a)this.Fa&&(this.Fa.send("SETUP_ACK"),this.Pb=l,Mc(this));else if(this.a.k()||this.Pb){var b=a.indexOf("|"),c=a.substring(0,b),a=a.substring(b+1),b=c.indexOf(",");if(-1==b){var d=c;this.Fa.send("ACK:"+d);Nc(this,a)}else if(d=c.substring(0,b),this.Fa.send("ACK:"+d),c=c.substring(b+1).split("/"),b=parseInt(c[0],10),c=parseInt(c[1],10),1==b&&(this.pb=[]),this.pb.push(a),b==c)Nc(this,this.pb.join("")),delete this.pb}};
Y.prototype.Bc=function(a){"SETUP_ACK"==a?(this.fa=o,this.Gc=l,Mc(this)):this.a.k()&&this.fa&&(a=parseInt(a.split(":")[1],10),a==this.mb&&(this.fa=o,Oc(this)))};var Oc=function(a){if(!a.fa&&a.Ia.length){var b=a.Ia.shift();++a.mb;a.$b.send(a.mb+b);a.fa=l}},Nc=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),c=b.substring(c+1);a.a.k()?a.a.C(d,c):(a.sa||(a.sa=[])).push({Kc:d,ab:c})};Y.prototype.Ra=3800;
Y.prototype.send=function(a,b){var c=a+":"+b;if(!J||b.length<=this.Ra)this.Ia.push("|"+c);else for(var d=b.length,f=Math.ceil(d/this.Ra),e=0,g=1;e<d;)this.Ia.push(","+g+"/"+f+"|"+c.substr(e,this.Ra)),g++,e+=this.Ra;Oc(this)};Y.prototype.d=function(){Y.l.d.call(this);var a=Pc;sa(a,this.Eb);sa(a,this.Db);this.Eb=this.Db=n;Hb(this.da);Hb(this.ca);this.Xa=this.Wa=this.da=this.ca=n};
var Pc=[],Rc=function(){var a=o;try{for(var b=0,c=Pc.length;b<c;b++){var d;if(!(d=a)){var f=Pc[b],e=f.Wb.location.href;if(e!=f.Vb){f.Vb=e;var g=e.split("#")[1];g&&(g=g.substr(1),f.Nc(decodeURIComponent(g)));d=l}else d=o}a=d}}catch(i){if(Pc[b].g.a.close(),!Pc.length)return}b=x();a&&(Bc=b);a=1E3>b-Bc?10:100;Cc=window.setTimeout(Qc,a)},Qc=v(Rc,Y),Sc=function(){Bc=x();Cc&&window.clearTimeout(Cc);Cc=window.setTimeout(Qc,10)},Lc=function(a,b){this.oa=a;this.vc=b;this.xb=0};
Lc.prototype.send=function(a){this.xb=++this.xb%2;a=this.oa+"#"+this.xb+encodeURIComponent(a);try{L?this.vc.location.href=a:this.vc.location.replace(a)}catch(b){}Sc()};var Kc=function(a,b,c){this.g=a;this.Wb=b;this.Nc=c;this.Vb=this.Wb.location.href.split("#")[0]+"#INITIAL";Pc.push(this);Sc()};var Vc=function(a,b){this.i=b||Q();this.a=a;this.Ec=this.a.h.pru;this.Nb=this.a.h.ifrid;L&&(Tc||(Tc=window.setTimeout(function(){Uc()},1E3)))};z(Vc,W);if(L)var Wc=[],Tc=0,Uc=function(a){for(var b=x(),a=a||3E3;Wc.length&&b-Wc[0].timestamp>=a;){var c=Wc.shift().Mc;Hb(c)}Tc=window.setTimeout(Xc,1E3)},Xc=function(){Uc()};var Yc={};Vc.prototype.X=3;Vc.prototype.r=function(){this.b().xpcRelay||(this.b().xpcRelay=Zc);this.send("tp","SETUP")};
var Zc=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),f=b.substr(c+1);if(!J||-1==(c=d.indexOf("|")))var e=d;else{var e=d.substr(0,c),d=d.substr(c+1),c=d.indexOf("+"),g=d.substr(0,c),c=parseInt(d.substr(c+1),10),i=Yc[g];i||(i=Yc[g]={sc:[],tc:0,rc:0});-1!=d.indexOf("++")&&(i.rc=c+1);i.sc[c]=f;i.tc++;if(i.tc!=i.rc)return;f=i.sc.join("");delete Yc[g]}V[a].C(e,decodeURIComponent(f))};Vc.prototype.jb=function(a){"SETUP"==a?(this.send("tp","SETUP_ACK"),this.a.F()):"SETUP_ACK"==a&&this.a.F()};
Vc.prototype.send=function(a,b){var c=encodeURIComponent(b),d=c.length,f=1800;if(J&&d>f){var e;e=2147483648;e=Math.floor(Math.random()*e).toString(36)+Math.abs(Math.floor(Math.random()*e)^x()).toString(36);for(var g=0,i=0;g<d;i++){var m=c.substr(g,f),g=g+f,j=e+(g>=d?"++":"+")+i;$c(this,a,m,j)}}else $c(this,a,c)};
var $c=function(a,b,c,d){if(J){var f=a.b().document.createElement("div");f.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';f=f.childNodes[0];f.xpcOnload=ad}else f=a.b().document.createElement("iframe"),L?Wc.push({timestamp:x(),Mc:f}):nb(f,"load",ad);var e=f.style;e.visibility="hidden";e.width=f.style.height="0px";e.position="absolute";e=a.Ec;e+="#"+a.a.name;a.Nb&&(e+=","+a.Nb);e+="|"+b;d&&(e+="|"+d);e+=":"+c;f.src=e;a.b().document.body.appendChild(f)},ad=function(){Hb(this)};
Vc.prototype.d=function(){Vc.l.d.call(this);L&&Uc(0)};var Z=function(a,b,c,d,f){this.i=c||Q();this.a=a;this.aa=f||2;this.Ta=b||"*";this.Ua=new Kb(this);this.na=new yb(100,this.b());this.Va=!!d;this.L=new U;this.K=new U;this.M=new U;this.yc=zc();this.Aa=n;this.Va?1==X(this.a)?uc(this.M,this.L):uc(this.M,this.K):(uc(this.M,this.L),2==this.aa&&uc(this.M,this.K));tc(this.M,this.Cb,n,this);this.M.B(l);var a=this.Ua,b=this.na,c=this.Bb,e,g,d="tick";"array"!=ba(d)&&(Lb[0]=d,d=Lb);for(f=0;f<d.length;f++){var i=nb(b,d[f],c||a,e||o,g||a.za||a);a.e.push(i)}};
z(Z,W);Z.prototype.m=n;Z.prototype.S=o;Z.prototype.X=1;var bd={},dd=function(a){var b=a.qa().data;if(!u(b))return o;var c=b.indexOf("|"),d=b.indexOf(":");if(-1==c||-1==d)return o;var f=b.substring(0,c),c=b.substring(c+1,d),b=b.substring(d+1);if(d=V[f])return d.C(c,b,a.qa().origin),l;var a=cd(b)[0],e;for(e in V)if(d=V[e],1==X(d)&&!d.k()&&"tp"==c&&("SETUP"==a||"SETUP_NTPV2"==a))return d.name=f,delete V[e],V[f]=d,d.C(c,b),l;return o};
Z.prototype.jb=function(a){var b=cd(a),a=b[0],b=b[1];switch(a){case "SETUP_ACK":ed(this,1);this.L.v||this.L.B(l);break;case "SETUP_ACK_NTPV2":2==this.aa&&(ed(this,2),this.L.v||this.L.B(l));break;case "SETUP":ed(this,1);fd(this,1);break;case "SETUP_NTPV2":2==this.aa&&(a=this.m,ed(this,2),fd(this,2),(1==a||this.Aa!=n)&&this.Aa!=b&&gd(this),this.Aa=b)}};
var gd=function(a){if(2==a.aa&&(a.m==n||2==a.m)){var b="SETUP_NTPV2",b=b+",",b=b+a.yc;a.send("tp",b)}(a.m==n||1==a.m)&&a.send("tp","SETUP")},fd=function(a,b){if(2==a.aa&&(a.m==n||2==a.m)&&2==b)a.send("tp","SETUP_ACK_NTPV2");else if((a.m==n||1==a.m)&&1==b)a.send("tp","SETUP_ACK");else return;a.K.v||a.K.B(l)},ed=function(a,b){b>a.m&&(a.m=b);1==a.m&&(!a.K.v&&!a.Va&&a.K.B(l),a.Aa=n)};r=Z.prototype;
r.r=function(){var a=this.b(),b=ha(a),c=bd[b];"number"==typeof c||(c=0);0==c&&nb(a.postMessage?a:a.document,"message",dd,o,Z);bd[b]=c+1;this.S=l;this.Bb()};r.Bb=function(){var a=0==X(this.a);this.Va&&a||this.a.k()||this.Y?this.na.stop():(this.na.start(),gd(this))};r.send=function(a,b){var c=this.a.D;if(c){var d=c.postMessage?c:c.document;this.send=function(a,b){var c=this,i=this.a.name,m=function(){c.Da=0;d.postMessage(i+"|"+a+":"+b,c.Ta)};this.Da=Ab(m,0)};this.send(a,b)}};
r.Cb=function(){var a=1==this.aa||1==this.m?200:k;this.a.F(a)};r.d=function(){if(this.S){var a=this.b(),b=ha(a),c=bd[b];bd[b]=c-1;1==c&&pb(a.postMessage?a:a.document,"message",dd,o,Z)}this.Da&&(xb.clearTimeout(this.Da),this.Da=0);F(this.Ua);delete this.Ua;F(this.na);delete this.na;this.L.cancel();delete this.L;this.K.cancel();delete this.K;this.M.cancel();delete this.M;delete this.send;Z.l.d.call(this)};var cd=function(a){a=a.split(",");a[1]=a[1]||n;return a};var hd=function(a,b){this.i=b||Q();this.a=a;this.Hb=a.at||"";this.Jb=a.rat||"";var c=this.b();if(!c.nix_setup_complete){var d="Class GCXPC____NIXVBS_wrapper\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport.GCXPC____NIXJS_handle_message(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport.GCXPC____NIXJS_create_channel(channel)\nEnd Sub\nPublic Sub GCXPC____NIXVBS_container()\n End Sub\nEnd Class\n Function GCXPC____NIXVBS_get_wrapper(transport, auth)\nDim wrap\nSet wrap = New GCXPC____NIXVBS_wrapper\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet GCXPC____NIXVBS_get_wrapper = wrap\nEnd Function";
try{c.execScript(d,"vbscript"),c.nix_setup_complete=l}catch(f){}}this.GCXPC____NIXJS_handle_message=this.Z;this.GCXPC____NIXJS_create_channel=this.Hc};z(hd,W);r=hd.prototype;r.X=6;r.ga=o;r.W=n;r.r=function(){0==X(this.a)?this.Tb():this.Ob()};r.Tb=function(){if(!this.ga){var a=this.a.$;try{a.contentWindow.opener=this.b().GCXPC____NIXVBS_get_wrapper(this,this.Hb),this.ga=l}catch(b){}this.ga||this.b().setTimeout(v(this.Tb,this),100)}};
r.Ob=function(){if(!this.ga){try{var a=this.b().opener;if(a&&"GCXPC____NIXVBS_container"in a){this.W=a;var b=this.W.GetAuthToken();if(b!=this.Jb)return;this.W.CreateChannel(this.b().GCXPC____NIXVBS_get_wrapper(this,this.Hb));this.ga=l;this.a.F()}}catch(c){return}this.ga||this.b().setTimeout(v(this.Ob,this),100)}};r.Hc=function(a){this.W=a;a=this.W.GetAuthToken();a==this.Jb&&this.a.F()};r.Z=function(a,b){var c=function(){var c;this.a.C(a,b,c)};this.b().setTimeout(v(c,this),1)};
r.send=function(a,b){this.W.SendMessage(a,b)};r.d=function(){hd.l.d.call(this);this.W=n};var jd=function(a,b){this.Ca={};for(var c=0,d;d=xc[c];c++)d in a&&!/^https?:\/\//.test(a[d])&&h(Error("URI "+a[d]+" is invalid for field "+d));this.h=a;this.name=this.h.cn||zc();this.i=b||Q();this.Ba=[];this.Za=new Kb(this);a.lpu=a.lpu||$b(this.i.b().location.href)+"/robots.txt";a.ppu=a.ppu||$b(a.pu||"")+"/robots.txt";V[this.name]=this;nb(window,"unload",id)};z(jd,Ub);var kd=/^%*tp$/,ld=/^%+tp$/;r=jd.prototype;r.R=n;r.T=n;r.g=n;r.nb=1;r.k=function(){return 2==this.nb};r.D=n;r.$=n;
var Fc=function(a){try{return!!a.D&&!Boolean(a.D.closed)}catch(b){return o}};r=jd.prototype;r.r=function(a){this.lb=a||aa;this.T?tc(this.T,this.uc,n,k):this.uc()};
r.uc=function(){this.T=n;this.h.ifrid&&(this.$=u(this.h.ifrid)?this.i.ba.getElementById(this.h.ifrid):this.h.ifrid);if(this.$){var a=this.$.contentWindow;a||(a=window.frames[this.h.ifrid]);this.D=a}this.D||(window==window.top&&h(Error("CrossPageChannel: Can't connect, peer window-object not set.")),this.D=window.parent);if(!this.g){if(!this.h.tp){var a=this.h,b;if(da(document.postMessage)||da(window.postMessage)||J&&window.postMessage)b=1;else if(K)b=2;else if(J&&this.h.pru)b=3;else{var c;if(c=J){c=
o;try{b=window.opener,window.opener={},c=db(window,"opener"),window.opener=b}catch(d){}}b=c?6:4}a.tp=b}switch(this.h.tp){case 1:a=this.h.nativeProtocolVersion||2;this.g=new Z(this,this.h.ph,this.i,!!this.h.osh,a);break;case 6:this.g=new hd(this,this.i);break;case 2:this.g=new Ac(this,this.i);break;case 3:this.g=new Vc(this,this.i);break;case 4:this.g=new Y(this,this.i)}this.g||h(Error("CrossPageChannel: No suitable transport found!"))}for(this.g.r();0<this.Ba.length;)this.Ba.shift()()};
r.close=function(){this.T&&(this.T.cancel(),this.T=n);this.Ba.length=0;var a=this.Za;qa(a.e,qb);a.e.length=0;this.nb=3;F(this.g);this.lb=this.g=n;F(this.R);this.R=n};r.F=function(a){this.k()||this.R&&0!=this.R.ma||(this.nb=2,F(this.R),a?(this.R=new Bb(this.lb,a),this.R.start()):(this.R=n,this.lb()))};r.Cb=jd.prototype.F;r.send=function(a,b){this.k()&&(Fc(this)?(ea(b)&&(b=Qb(b)),this.g.send(md(a),b)):this.close())};
r.C=function(a,b,c){if(this.T)this.Ba.push(v(this.C,this,a,b,c));else{var d=this.h.ph;if((c=/^[\s\xa0]*$/.test(c==n?"":""+c)||/^[\s\xa0]*$/.test(d==n?"":""+d)||c==this.h.ph)&&!this.Y)if(!a||"tp"==a)this.g.jb(b);else if(this.k()&&(a=a.replace(/%[0-9a-f]{2}/gi,decodeURIComponent),a=ld.test(a)?a.substring(1):a,c=b,(d=this.Ca[a])?a=d:this.Kb?(a=ka(this.Kb,a),c=ea(c),a={B:a,Ub:c}):a=n,a))b=Wb(b,a.Ub),b!=n&&a.B(b)}};
var md=function(a){kd.test(a)&&(a="%"+a);return a.replace(/[%:|]/g,encodeURIComponent)},X=function(a){var b=a.h.role;return b?b:window.parent==a.D?1:0};jd.prototype.d=function(){this.close();this.$=this.D=n;delete V[this.name];F(this.Za);delete this.Za;jd.l.d.call(this)};var id=function(){for(var a in V)F(V[a])};var $=function(a,b,c){u(b)?nd(a,c,b):ya(b,ka(nd,a))},nd=function(a,b,c){a.style[(""+c).replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})]=b},od=function(a,b){var c;a:{c=b;var d=Eb(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,n))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}return c||(a.currentStyle?a.currentStyle[b]:n)||a.style&&a.style[b]},pd=function(a){if(Pa&&L){var b=a.ownerDocument.defaultView;if(b!=b.top)return o}return!!a.getBoundingClientRect},
qd=function(a){var b=a.getBoundingClientRect();J&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b},rd=function(a){if(J&&!$a(8))return a.offsetParent;for(var b=Eb(a),c=od(a,"position"),d="fixed"==c||"absolute"==c,a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=od(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||
"relative"==c))return a;return n},sd=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;var td=function(a){a=a||A.location.protocol+"//"+A.location.host;return a+"/robots.txt"};var ud=function(a,b,c,d,f,e){this.u=o;this.zb=a;this.bb=f;this.gc=e;this.Ab=b;this.t=+c;this.s=+d;this.Na=[]};ud.prototype.Ea=function(){return this.u};ud.prototype.eb=function(){return this.t};ud.prototype.cb=function(){return this.s};ud.prototype.collapse=function(){var a=vd(this);if(a){for(var a=0,b=this.Na.length;a<b;a++){var c=this.Na[a];c.qc.style[c.bd]=c.cd}this.Na.length=0;this.u=o}};
var xd=function(a,b){wd(a,b,"zIndex","999999")},yd=function(a){var b=[],c=vd(a);if(!c)return b;b.push(c);a.bb&&a.gc&&b.push(a.bb.document.getElementById(a.gc));return b};
ud.prototype.expand=function(a,b,c){var d=yd(this);if(!(0>=d.length)){for(var f=0,e=d.length;f<e;++f){var g=d[f],i=b;wd(this,g,"width",a+"px");wd(this,g,"height",i+"px");xd(this,g)}d=d[d.length-1];a>this.t&&(0==c||3==c)&&wd(this,d,"left","-"+(a-this.t)+"px");b>this.s&&(1==c||0==c)&&wd(this,d,"top","-"+(b-this.s)+"px");a=d.parentNode;b=a.parentNode;"ins"==a.nodeName.toLowerCase()&&(xd(this,a),xd(this,b));for(a=b.parentNode;a&&a.style&&"body"!=a.nodeName.toLowerCase();a=a.parentNode)"visible"!=a.style.overflow&&
wd(this,a,"overflow","visible");this.u=l}};var vd=function(a){a.wc||(a.wc=A.getElementById(a.zb));return a.wc},wd=function(a,b,c,d){a.Na.push(new zd(b,c,d))},zd=function(a,b,c){this.qc=a;this.bd=b;this.cd=a.style[b];this.qc.style[b]=c};var Ad=function(a,b){this.N=a;this.zc=b;var c;c=a.Ab;var d=A.URL;d instanceof R||(d=kc(d));c instanceof R||(c=kc(c));var f=d,d=c;c=f.O();var e=!!d.G;e?ac(c,d.G):e=!!d.V;if(e){var g=c,i=d.V;S(g);g.V=i}else e=!!d.w;e?(g=c,i=d.w,S(g),g.w=i):e=d.P!=n;g=d.z;if(e)bc(c,d.P);else if(e=!!d.z)if("/"!=g.charAt(0)&&(f.w&&!f.z?g="/"+g:(f=c.z.lastIndexOf("/"),-1!=f&&(g=c.z.substr(0,f+1)+g))),".."==g||"."==g)g="";else if(!(-1==g.indexOf("./")&&-1==g.indexOf("/."))){for(var f="/",f=0==g.lastIndexOf(f,0),g=g.split("/"),
i=[],m=0;m<g.length;){var j=g[m++];"."==j?f&&m==g.length&&i.push(""):".."==j?((1<i.length||1==i.length&&""!=i[0])&&i.pop(),f&&m==g.length&&i.push("")):(i.push(j),f=l)}g=i.join("/")}e?(f=c,S(f),f.z=g):e=""!==d.n.toString();e?cc(c,d.n.toString()?decodeURIComponent(d.n.toString()):""):e=!!d.U;e&&(e=c,d=d.U,S(e),e.U=d);d=c.G+"://"+c.w;c.P!=n&&(d+=":"+c.P);this.Ta=c=d;c=this.N;d={};d.ifrid=c.zb;d.pu=c.Ab;d.cn=this.zc;d.ppu=td(this.Ta);d.lpu=td();c=d;this.a=new jd(c);Vb(this.a,v(this.Z,this));this.Fb();
window.setTimeout(v(this.Ya,this),3E4)};Ad.prototype.Fb=function(){if(this.a)try{this.a.r()}catch(a){window.setTimeout(v(this.Fb,this),10)}};Ad.prototype.Ya=function(){this.a&&!this.a.k()&&(this.a.g.r=function(){},1==this.a.g.X&&(this.a.g.ld=function(){}),4==this.a.g.X&&(this.a.g.kd=function(){}),this.a.g.ea(),this.a.ea())};
Ad.prototype.Z=function(a){var b=a.split("_"),a=b[0];if("expand"==a){if(!this.N.Ea()){for(var c=a=0,d=0;d<b.length;++d){var f=b[d].charAt(0);"w"==f?a=parseInt(b[d].substring(1),10):"h"==f&&(c=parseInt(b[d].substring(1),10))}var b=this.N,f=a,d=c,e=yd(b),e=e[e.length-1],g,i=new P;if(1==e.nodeType){if(pd(e)){var m=qd(e);i.x=m.left;i.y=m.top}else{var m=Jb(Q(e)),j;var p=e,s=Eb(p),w=od(p,"position"),T=K&&s.getBoxObjectFor&&!p.getBoundingClientRect&&"absolute"==w&&(j=s.getBoxObjectFor(p))&&(0>j.screenX||
0>j.screenY),q=new P(0,0),G;j=s?Eb(s):document;if(G=J)if(G=!$a(9))G=Q(j),G="CSS1Compat"==G.ba.compatMode,G=!G;G=G?j.body:j.documentElement;if(p!=G)if(pd(p))j=qd(p),p=Jb(Q(s)),q.x=j.left+p.x,q.y=j.top+p.y;else if(s.getBoxObjectFor&&!T)j=s.getBoxObjectFor(p),p=s.getBoxObjectFor(G),q.x=j.screenX-p.screenX,q.y=j.screenY-p.screenY;else{j=p;do{q.x+=j.offsetLeft;q.y+=j.offsetTop;j!=p&&(q.x+=j.clientLeft||0,q.y+=j.clientTop||0);if(L&&"fixed"==od(j,"position")){q.x+=s.body.scrollLeft;q.y+=s.body.scrollTop;
break}j=j.offsetParent}while(j&&j!=p);if(Oa||L&&"absolute"==w)q.y-=s.body.offsetTop;for(j=p;(j=rd(j))&&j!=s.body&&j!=G;)if(q.x-=j.scrollLeft,!Oa||"TR"!=j.tagName)q.y-=j.scrollTop}j=q;i.x=j.x-m.x;i.y=j.y-m.y}if(K&&!M(12)){J?g="-ms-transform":L?g="-webkit-transform":Oa?g="-o-transform":K&&(g="-moz-transform");var B;g&&(B=od(e,g));B||(B=od(e,"transform"));B?(g=B.match(sd),g=!g?new P(0,0):new P(parseFloat(g[1]),parseFloat(g[2]))):g=new P(0,0);i=new P(i.x+g.x,i.y+g.y)}}else g=da(e.qa),B=e,e.targetTouches?
B=e.targetTouches[0]:g&&e.qa().targetTouches&&(B=e.qa().targetTouches[0]),i.x=B.clientX,i.y=B.clientY;g=i;B=b.bb||window;B=Fb(B||window);f-=b.t;e=d-b.s;d=g.y;e=e>d;i=B.height-(g.y+b.s);d=e||i>=d;e=g.x;f=f>e;b=B.width-(g.x+b.t);b=f||b>=e;f=2;d&&!b?f=3:!d&&b?f=1:!d&&!b&&(f=0);b=f;this.N.expand(a,c,b);this.a.send("expandable_ad","ok_expand_w"+a+"_h"+c+"_d"+b)}}else"collapse"==a&&this.N.Ea()&&(this.N.collapse(),this.a.send("expandable_ad","ok_collapse_w"+this.N.eb()+"_h"+this.N.cb()))};
var Cd=function(a){var b=a.google_frame_id;b||(b="google_frame_"+Math.floor(2147483647*Math.random()));var c=a.google_ad_url,d=parseInt(a.google_ad_width,10),f=parseInt(a.google_ad_height,10),e=a.google_container_id,c=Bd(b,c,d,f,e);return a[b]=c};y("ExpandableAdSlotFactory.createIframeFromWindow",Cd);
var Bd=function(a,b,c,d,f,e,g){if(!a||!b||0>=c||0>=d)return n;var i=zc(),m=na(A.URL),b=Dd(b,i,m),m=a,j="<iframe allowtransparency=true frameborder=0 height="+d+" hspace=0 id="+m+" marginheight=0 marginwidth=0 name="+m+' scrolling=no src="'+b+'" style="left:0;position:absolute;top:0" vspace=0 width='+c+"></iframe>";if(g)m=j;else var p="border:none;height:"+d+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+c+"px",m=['<ins style="display:inline-table;',p,'">','<ins id="',m+"_anchor",
'" style="display:block;',p,'">',j,"</ins></ins>"],m=m.join("");(f=f?A.getElementById(f):n)?f.innerHTML=m:A.write(m);a=new ud(a,b,c,d,e,g);return new Ad(a,i)};y("ExpandableAdSlotFactory.createIframe",Bd);function Dd(a,b,c){return a+(-1==a.indexOf("?")?"?":"&")+(c?"google_debug&":"")+"xpc="+b+"&p="+encodeURIComponent(A.location.protocol)+"//"+encodeURIComponent(A.location.host)}
var Ed=function(a,b,c,d){if(!a||!b||0>=c||0>=d)return n;var f=zc(),e=na(A.URL),b=Dd(b,f,e),e=a,g=b,i=c,m=d,j=document.createElement("iframe");j.style.cssText="border:none;height:"+m+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+i+"px";j.name=e;j.id=e;j.src=g;j.style.cssText="left:0;position:absolute;top:0";j.width=i;j.height=m;j.frameBorder=0;j.hspace=0;j.vspace=0;j.scrolling="no";j.nd=0;j.od=0;j.md=l;e=j;b=new ud(a,b,c,d);window["expandableAdSlot_"+a]=new Ad(b,f);a=e;c="border:none;height:"+
d+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+c+"px";d=A.createElement("ins");d.style.cssText="display:inline-table;"+c;f=A.createElement("ins");f.style.cssText="display:block;"+c;f.appendChild(a);d.appendChild(f);return c=d};y("DhtmlExpandableIframeFactory.createElement",Ed);var Fd=function(){this.u=this.j=o;this.ib=l;this.t=this.s=this.Ha=this.Ga=0;this.Q=o;this.Ic=5E3;this.Sb=2E3;this.Jc=100;this.ra=this.Rb=0;this.kb={};this.gb="google_expansion_overlay";this.hb="google_progress_bar"},Gd=function(a,b){a.j=l;if(!b)return a.j=o,a.j;"number"!=typeof b.width&&(a.j=o);"number"!=typeof b.height&&(a.j=o);"function"!=typeof b.expansionCallback&&(a.j=o);"function"!=typeof b.collapseCallback&&(a.j=o);if(a.j){a.Ga=b.height;a.Ha=b.width;a.Yb=b.expansionCallback;a.ec=b.collapseCallback;
var c=A.body;ma(c,"mousedown",v(a.Vc,a));J?(ma(c,"mouseenter",v(a.jc,a)),ma(c,"mouseleave",v(a.kc,a))):(ma(c,"mouseover",v(a.jc,a)),ma(c,"mouseout",v(a.kc,a)))}return a.j};r=Fd.prototype;r.cb=function(){return this.s};r.eb=function(){return this.t};r.Wc=function(){return this.Ga};r.Xc=function(){return this.Ha};r.Ea=function(){return this.u};r.Yc=function(){return this.j};r.Zc=function(a){this.ib=a};
var Jd=function(a,b,c,d){a.u=l;if(a.ib){var f=a,e=c,g=d;if(0==g||3==g){var i=b-f.t;0<i&&(A.body.style.marginLeft=i+"px")}if(0==g||1==g)f=e-f.s,0<f&&(A.body.style.marginTop=f+"px")}if(f=A.getElementById("abgc"))f.style.visibility="hidden";Hd(a);Id(a,"expansion");"function"==typeof a.Yb&&a.Yb(b,c,d)},Kd=function(a,b,c){a.u=o;a.ib&&(A.body.style.marginLeft="0",A.body.style.marginTop="0");var d=A.getElementById("abgc");d&&(d.style.visibility="visible");Hd(a);Id(a,"contraction");"function"==typeof a.ec&&
a.ec(b,c)};Fd.prototype.Vc=function(){this.Qc=new Date};Fd.prototype.kc=function(){clearTimeout(this.Rb);Hd(this);this.Q=o};Fd.prototype.jc=function(){this.Q=l};
var Hd=function(a){clearInterval(a.Xb);clearInterval(a.ra);a.ra=0;var b=A.getElementById(a.gb),a=A.getElementById(a.hb);b&&a&&(b.style.display="none",b.style.bottom="-20px",a.style.width="0%")},Id=function(a,b){if(C.CREATIVE_CONVERSION_URL){var c;c=C.ENABLE_CPE_EXPANSION&&C.CLICK_URL&&"expansion"===b&&!a.kb[b]?C.CLICK_URL:[C.CREATIVE_CONVERSION_URL,"&label=",b,a.kb[b]?"&noconv=1":"","&random=",(new Date).getTime()].join("");a.kb[b]=l;var d=C;d.google_image_requests||(d.google_image_requests=[]);var f=
d.document.createElement("img");f.src=c;d.google_image_requests.push(f)}},Ld=function(a){y("CreativeToolset",a);y("CreativeToolset.prototype.collapseWindow",a.prototype.lc);y("CreativeToolset.prototype.enableExpansion",a.prototype.mc);y("CreativeToolset.prototype.expandWindow",a.prototype.nc);y("CreativeToolset.prototype.getCollapsedHeight",a.prototype.cb);y("CreativeToolset.prototype.getCollapsedWidth",a.prototype.eb);y("CreativeToolset.prototype.getExpandedHeight",a.prototype.Wc);y("CreativeToolset.prototype.getExpandedWidth",
a.prototype.Xc);y("CreativeToolset.prototype.isExpanded",a.prototype.Ea);y("CreativeToolset.prototype.isExpansionEnabled",a.prototype.Yc);y("CreativeToolset.prototype.shouldMaintainCoordinates",a.prototype.Zc)};var Md=function(){Fd.call(this)};z(Md,Fd);r=Md.prototype;r.mc=function(a){return Gd(this,a)&&this.yb()?l:o};r.yb=function(){var a=Fb(C||window);this.t=a.width;this.s=a.height;return"function"==typeof iframer.expand&&"function"==typeof iframer.collapse?(this.Pc=iframer.expand,this.Sc=iframer.collapse,l):o};r.nc=function(a,b){if(this.j&&!this.u&&0==this.ra&&this.Q){var c=this.Ha,d=this.Ga;a&&b&&(c=a,d=b);this.Pc({width:c,height:d},v(this.Tc,this))}};
r.lc=function(){this.j&&this.u&&this.Sc({},v(this.$c,this))};r.Tc=function(a){Jd(this,a.width,a.height,a.direction)};r.$c=function(){Kd(this,this.t,this.s)};
r.Z=function(a){a=a.split("_");if("ok"==a[0]){for(var b,c,d,f=2;f<a.length;++f){var e=a[f].charAt(0),g=parseInt(a[f].substring(1),10);"w"==e?b=g:"h"==e?c=g:"d"==e&&(d=g)}"expand"==a[1]&&"number"==typeof b&&"number"==typeof c&&"number"==typeof d&&0<b&&0<c&&0<=d?Jd(this,b,c,d):"collapse"==a[1]&&("number"==typeof b&&"number"==typeof c&&0<b&&0<c)&&Kd(this,b,c)}};window.USE_IFRAMES_API===l&&Ld(Md);var Nd=function(){Fd.call(this)};z(Nd,Fd);r=Nd.prototype;r.mc=function(a){return Gd(this,a)?(this.yb(A.URL),l):o};r.yb=function(a){var b=Fb(C||window);this.t=b.width;this.s=b.height;var b=new R(a),a=b.n.get("xpc"),b=b.n.get("p"),c={};c.cn=a;c.ph=b;c.ppu=td(b);c.lpu=td();a=c;this.a=new jd(a);Vb(this.a,v(this.Z,this));this.a.r(function(){});window.setTimeout(v(this.Ya,this),3E4)};r.Ya=function(){this.a&&!this.a.k()&&(this.a=n)};
r.nc=function(a,b){if(this.j&&!this.u&&0==this.ra&&this.Q){var c=this.Ha,d=this.Ga;a&&b&&(c=a,d=b);var f="expand_w"+c+"_h"+d,e=c=v(function(){Od(this,f)},this);if("function"==typeof e)if(c=v(function(){this.Q&&this.Q&&e()},this),new Date-this.Qc<this.Ic)c();else{this.Rb=setTimeout(c,this.Sb);var g=A.getElementById(this.gb),i=A.getElementById(this.hb);if(!g){var m=C.EXPANSION_TEXT||"Expanding...",c=C.EXPANSION_RIGHT_TO_LEFT&&"string"!==typeof C.EXPANSION_RIGHT_TO_LEFT||o,d=9999999,g=A.createElement("div");
g.id=this.gb;var j=A.createElement("span");j.innerHTML=m;j.style.fontSize="14px";j.style.fontFamily="Verdana, sans-serif";j.style.letterSpacing="0.05em";j.style.position="absolute";j.style.bottom="1px";j.style.zIndex=d;i=A.createElement("div");i.id=this.hb;i.style.zIndex=d;i.style.background="#eee";i.style.width="0%";i.style.height="20px";c?(j.style.right="5px",i.style.cssFloat="right"):j.style.left="5px";g.appendChild(j);g.appendChild(i);A.body.appendChild(g);m=g.style;m.position="absolute";c?(m.right=
0,$(g,"border-top-left-radius","5px"),$(g,"-moz-border-top-left-radius","5px"),$(g,"-webkit-border-top-left-radius","5px"),m.textAlign="right"):(m.left=0,$(g,"border-top-right-radius","5px"),$(g,"-moz-border-top-right-radius","5px"),$(g,"-webkit-border-top-right-radius","5px"),m.textAlign="left");m.bottom="-20px";m.padding=0;m.height="20px";m.width="120px";m.lineHeight="20px";m.overflow="hidden";m.zIndex=d;m.opacity=0.75;m.filter="alpha(opacity=75)";m.background="#aaa";$(g,"pointer-events","none");
$(g,"-moz-opacity","0.75");$(g,"-webkit-opacity","0.75")}Hd(this);g.style.display="";var p=20,s=0,c=v(function(){if(!this.Q||p<=0)clearInterval(this.Xb);else{p=p-1;g.style.bottom="-"+p+"px"}},this),d=v(function(){if(!this.Q||s>=100)Hd(this);else{s=s+1;i.style.width=s+"%"}},this);this.Xb=setInterval(c,this.Jc/p);this.ra=setInterval(d,this.Sb/100)}}};r.lc=function(){this.j&&this.u&&Od(this,"collapse")};var Od=function(a,b){a.a&&a.a.k()&&a.a.send("expandable_ad",b)};
Nd.prototype.Z=function(a){a=a.split("_");if("ok"==a[0]){for(var b,c,d,f=2;f<a.length;++f){var e=a[f].charAt(0),g=parseInt(a[f].substring(1),10);"w"==e?b=g:"h"==e?c=g:"d"==e&&(d=g)}"expand"==a[1]&&"number"==typeof b&&"number"==typeof c&&"number"==typeof d&&0<b&&0<c&&0<=d?Jd(this,b,c,d):"collapse"==a[1]&&("number"==typeof b&&"number"==typeof c&&0<b&&0<c)&&Kd(this,b,c)}};window.USE_IFRAMES_API!==l&&Ld(Nd);na(document.URL)&&document.write('<script src="https://web.archive.org/web/20120616045339/http://pagead2.googlesyndication.com/pagead/expansion_embed_dbg.js"><\/script>');})()

}

/*
     FILE ARCHIVED ON 04:53:39 Jun 16, 2012 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:16:34 Jun 16, 2026.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  capture_cache.get: 0.398
  load_resource: 57.128
  PetaboxLoader3.resolve: 34.093
  PetaboxLoader3.datanode: 21.447
*/