var _____WB$wombat$assign$function_____=function(name){return (globalThis._wb_wombat && globalThis._wb_wombat.local_init && globalThis._wb_wombat.local_init(name))||globalThis[name];};if(!globalThis.__WB_pmw){globalThis.__WB_pmw=function(obj){this.__WB_source=obj;return this;}}{
let window = _____WB$wombat$assign$function_____("window");
let self = _____WB$wombat$assign$function_____("self");
let document = _____WB$wombat$assign$function_____("document");
let location = _____WB$wombat$assign$function_____("location");
let top = _____WB$wombat$assign$function_____("top");
let parent = _____WB$wombat$assign$function_____("parent");
let frames = _____WB$wombat$assign$function_____("frames");
let opener = _____WB$wombat$assign$function_____("opener");
(function(){var h=void 0,i=!0,j=null,m=!1,n=this,aa=function(a,b,c){a=a.split(".");c=c||n;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&b!==h?c[d]=b:c=c[d]?c[d]:c[d]={}},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=
typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},o=function(a){return"array"==ba(a)},ca=function(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length},q=function(a){return"string"==typeof a},da=function(a){var b=
typeof a;return"object"==b&&a!=j||"function"==b},ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return r.apply(j,
arguments)},ga=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}},s=function(a,b,c){aa(a,b,c)},ha=function(a,b,c){a[b]=c};var t=function(a,b){var c=parseFloat(a);return isNaN(c)||1<c||0>c?b:c},ia=function(a,b){return/^true$/.test(a)?i:/^false$/.test(a)?m:b},ja=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,ka=function(a,b){if(!a)return b;var c=a.match(ja);return c?c[0]:b};var la=t("0",0),ma=t("0",0),na=t("0",0),oa=t("0",0),pa=t("0",0),qa=t("0",0),ra=t("0.001",0),sa=t("0.02",0),ta=t("1",0),ua=t("0.01",0),va=t("0.01",
0);var wa=function(){var a="r20120606";return a},xa=ia("false",m),ya=ia("false",m),za=ia("false",m),Aa=ia("true",m);var Ba=function(){return ka("","pagead2.googlesyndication.com")},Ca=function(a){return a?"pagead2.googlesyndication.com":ka("","pagead2.googlesyndication.com")};var Ia=function(a,b){if(b)return a.replace(Da,"&amp;").replace(Ea,"&lt;").replace(Fa,"&gt;").replace(Ga,"&quot;");if(!Ha.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Da,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ea,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Fa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ga,"&quot;"));return a},Da=/&/g,Ea=/</g,Fa=/>/g,Ga=/\"/g,Ha=/[&<>\"]/,Ka=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(Ja,function(a,
e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var g=Number("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},La=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return a}})},Ja=/&([^;\s<&]+);?/g,Ma=function(a,b){for(var c=
b.length,d=0;d<c;d++){var e=1==c?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},Na={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},Oa={"'":"\\'"},Qa=function(a){a=""+a;if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0);b[c+1]=Na[d]||(31<e&&127>e?d:Pa(d))}b.push('"');return b.join("")},Pa=function(a){if(a in Oa)return Oa[a];if(a in
Na)return Oa[a]=Na[a];var b=a,c=a.charCodeAt(0);if(31<c&&127>c)b=a;else{if(256>c){if(b="\\x",16>c||256<c)b+="0"}else b="\\u",4096>c&&(b+="0");b+=c.toString(16).toUpperCase()}return Oa[a]=b},Ra=function(a,b){for(var c=0,d=(""+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=(""+b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",p=e[g]||"",k=RegExp("(\\d*)(\\D*)","g"),T=RegExp("(\\d*)(\\D*)","g");do{var D=k.exec(l)||["","",""],O=T.exec(p)||
["","",""];if(0==D[0].length&&0==O[0].length)break;var c=0==D[1].length?0:parseInt(D[1],10),db=0==O[1].length?0:parseInt(O[1],10),c=(c<db?-1:c>db?1:0)||((0==D[2].length)<(0==O[2].length)?-1:(0==D[2].length)>(0==O[2].length)?1:0)||(D[2]<O[2]?-1:D[2]>O[2]?1:0)}while(0==c)}return c};var u=function(a,b){this.width=a;this.height=b};u.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};u.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};u.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};u.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var v=document,w=window,Sa=function(a){var b=j;if((a=a.getElementsByTagName("script"))&&a.length)b=a[a.length-1],b=b.parentNode;return b},Ta=Sa(v);Ca();var x=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(j,a[c],c,a)},Ua=function(a){return!!a&&"function"==typeof a&&!!a.call},Va=function(a){return!!a&&("object"==typeof a||"function"==typeof a)},Wa=function(a,b){if(!a)return m;var c=i;x(b,function(b,e){if(!c||!(e in a)||typeof b!=typeof a[e])c=m});return c},Xa=function(a,b){if(2>arguments.length)return a.length;for(var c=1,d=arguments.length;c<d;++c)a.push(arguments[c]);return a.length};
function y(a){return"function"==typeof encodeURIComponent?encodeURIComponent(a):escape(a)}function Ya(a,b,c,d){var d=d||document,e=d.createElement("script");e.type="text/javascript";b&&(e.onreadystatechange!==h?e.onreadystatechange=function(){if("complete"==e.readyState||"loaded"==e.readyState)try{b()}catch(a){}}:e.onload=b);c&&(e.id=c);e.src=a;var f=d.getElementsByTagName("head")[0];if(!f)return m;window.setTimeout(function(){f.appendChild(e)},0);return i}
var Za=function(a,b,c){return a.addEventListener?(a.addEventListener(b,c,m),i):a.attachEvent?(a.attachEvent("on"+b,c),i):m},$a=function(a,b,c){return a.removeEventListener?(a.removeEventListener(b,c,m),i):a.detachEvent?(a.detachEvent("on"+b,c),i):m},ab=function(a){"google_onload_fired"in a||(a.google_onload_fired=m,Za(a,"load",function(){a.google_onload_fired=i}))},bb=function(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=a.document.createElement("img");c.src=b;a.google_image_requests.push(c)};
function cb(a){return a in eb?eb[a]:eb[a]=-1!=navigator.userAgent.toLowerCase().indexOf(a)}var eb={};
function fb(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else{if(navigator.userAgent&&0<=navigator.userAgent.indexOf("Windows CE")){for(var a=3,b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1)),a++}catch(c){b=j}return a.toString()}if(cb("msie")&&!window.opera){b=j;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),a=6,b.AllowScriptAccess="always"}catch(e){if(6==a)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(f){}}if(b)return a=b.GetVariable("$version").split(" ")[1],a.replace(/,/g,".")}}return"0"}function gb(a){var b=a.google_ad_format;return b?0<b.indexOf("_0ads"):"html"!=a.google_ad_output&&0<a.google_num_radlinks}function z(a){return!!a&&-1!=a.indexOf("_sdo")}
var hb=function(a,b){if(!(1.0E-4>Math.random())){var c=Math.random();if(c<b)return c=Math.floor(c/b*a.length),a[c]}return j},ib=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();window.screen&&(a.u_h=window.screen.height,a.u_w=window.screen.width,a.u_ah=window.screen.availHeight,a.u_aw=window.screen.availWidth,a.u_cd=window.screen.colorDepth);navigator.plugins&&(a.u_nplug=navigator.plugins.length);navigator.mimeTypes&&(a.u_nmime=navigator.mimeTypes.length)},
jb=function(a,b){var c=a.length;if(0==c)return 0;for(var d=b||305419896,e=0;e<c;e++)var f=a.charCodeAt(e),d=d^(d<<5)+(d>>2)+f&4294967295;return 0<d?d:4294967296+d},kb=function(a){if(!a)return"";for(var b=[],c=0;a&&25>c;a=a.parentNode,++c)b.push(a.id||"");return b.join()},lb=function(a){try{return!!a.location.href||""===a.location.href}catch(b){return m}};var mb=function(a,b,c,d){b="border:none;height:"+c+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+b+"px";a=['<ins style="display:inline-table;',b,'">','<ins id="',a,'" style="display:block;',b,'">',d,"</ins></ins>"];return a.join("")};var nb=function(a,b){for(var c=0,d=a,e=0;a!=a.parent;)if(a=a.parent,e++,lb(a))d=a,c=e;else if(b)break;return{win:d,level:c}},ob=function(a){a=nb(a,i);return a.win},pb=function(a){a=nb(a,m);return a.win},qb=j,rb=function(){qb||(qb=ob(window));return qb};var A=function(a){this.o=[];this.c=a||window;this.d=0;this.n=j},sb=function(a,b){this.fn=a;this.win=b};A.prototype.enqueue=function(a,b){0==this.d&&0==this.o.length&&(!b||b==window)?(this.d=2,this.G(new sb(a,window))):this.l(a,b)};A.prototype.l=function(a,b){this.o.push(new sb(a,b||this.c));this.q()};A.prototype.D=function(a){this.d=1;a&&(this.n=this.c.setTimeout(r(this.p,this),a))};A.prototype.p=function(){1==this.d&&(this.n!=j&&(this.c.clearTimeout(this.n),this.n=j),this.d=0);this.q()};
A.prototype.statusz=function(){return i};ha(A.prototype,"nq",A.prototype.enqueue);ha(A.prototype,"nqa",A.prototype.l);ha(A.prototype,"al",A.prototype.D);ha(A.prototype,"rl",A.prototype.p);ha(A.prototype,"sz",A.prototype.statusz);A.prototype.q=function(){this.c.setTimeout(r(this.Z,this),0)};A.prototype.Z=function(){if(0==this.d&&this.o.length){var a=this.o.shift();this.d=2;a.win.setTimeout(r(this.G,this,a),0);this.q()}};A.prototype.G=function(a){this.d=0;a.fn()};
var tb=function(a){try{return a.sz()}catch(b){return m}},ub=function(){var a=rb().google_jobrunner;Va(a)&&(tb(a)&&Ua(a.nq)&&Ua(a.nqa)&&Ua(a.al)&&Ua(a.rl))&&a.rl()};var B=!!window.google_async_iframe_id,C=B&&window.parent||window,E=function(){if(B&&!lb(C)){for(var a="."+v.domain;2<a.split(".").length&&!lb(C);)v.domain=a=a.substr(a.indexOf(".")+1),C=window.parent;lb(C)||(C=window)}return C},vb=function(a){B&&a!=a.parent&&(ub(),a.google_async_iframe_close&&a.setTimeout(function(){a.document.close()},0))},wb=function(){if(!B)return j;var a=window.google_async_iframe_id;if(a){for(var a=E().document.getElementById(a),b=0;a&&3>b;++b)a=a.parentNode;return a}return j};var F=Array.prototype,xb=F.indexOf?function(a,b,c){return F.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:0>c?Math.max(0,a.length+c):c;if(q(a))return!q(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},yb=F.forEach?function(a,b,c){F.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},zb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ab=function(a,
b,c){return 2>=arguments.length?F.slice.call(a,b):F.slice.call(a,b,c)};var G=function(a){this.defaultBucket=[];this.layers={};for(var b=0,c=arguments.length;b<c;++b)this.layers[arguments[b]]=""},Bb=function(a){for(var b=new G,c=0,d=a.defaultBucket.length;c<d;++c)b.defaultBucket.push(a.defaultBucket[c]);x(a.layers,r(G.prototype.t,b));return b};G.prototype.statusz=function(){return i};G.prototype.t=function(a,b){this.layers[b]=a};G.prototype.Y=function(a,b){return""==a?"":!b?(this.defaultBucket.push(a),a):this.layers.hasOwnProperty(b)?this.layers[b]=a:""};
G.prototype.a=function(a,b,c){return this.T(c)&&!(1.0E-4>Math.random())&&Math.random()<b?(b=Math.floor(Math.random()*a.length),this.Y(a[b],c)):""};G.prototype.T=function(a){return!a?i:this.layers.hasOwnProperty(a)&&""==this.layers[a]};G.prototype.b=function(a){return this.layers.hasOwnProperty(a)?this.layers[a]:""};G.prototype.geil=G.prototype.b;
G.prototype.P=function(){var a=[],b=function(b){""!=b&&a.push(b)};x(this.layers,b);return 0<this.defaultBucket.length&&0<a.length?this.defaultBucket.join(",")+","+a.join(","):this.defaultBucket.join(",")+a.join(",")};var Db=function(a){this.S=a;Cb(this)},Eb={google_persistent_state:i,google_persistent_state_async:i},Fb={},Gb=function(a){a=a&&Eb[a]?a:B?"google_persistent_state_async":"google_persistent_state";if(Fb[a])return Fb[a];if("google_persistent_state_async"==a)var b=E(),c={};else c=b=E();var d=b[a];return"object"!=typeof d||"object"!=typeof d.S?b[a]=Fb[a]=new Db(c):Fb[a]=d},Cb=function(a){H(a,3,j);H(a,4,0);H(a,5,0);H(a,6,0);H(a,7,(new Date).getTime());H(a,8,{});H(a,9,{});H(a,10,{});H(a,11,[]);H(a,12,0);
H(a,14,{})},Hb=function(a){switch(a){case 3:return"google_exp_persistent";case 4:return"google_num_sdo_slots";case 5:return"google_num_0ad_slots";case 6:return"google_num_ad_slots";case 7:return"google_correlator";case 8:return"google_prev_ad_formats_by_region";case 9:return"google_prev_ad_slotnames_by_region";case 10:return"google_num_slots_by_channel";case 11:return"google_viewed_host_channels";case 12:return"google_num_slot_to_show";case 14:return"gaGlobal"}},I=function(a,b){var c=Hb(b);return c=
a.S[c]},J=function(a,b,c){return a.S[Hb(b)]=c},H=function(a,b,c){a=a.S;b=Hb(b);return a[b]===h?a[b]=c:a[b]},Ib=function(a,b){return J(a,3,b)};var Jb,Kb,Lb=function(a){try{return a.statusz()}catch(b){return m}},K=function(){if(Jb&&Lb(Jb))return Jb;var a=Gb(),b=I(a,3);return!b||!Va(b)||!Wa(b,G.prototype)||!Lb(b)?Jb=Ib(a,new G(1,2,3,4,5,6,7,9)):Jb=b},Mb=function(){Kb||(Kb=Bb(K()));return Kb},Nb={ASWIFT_BAD_BLACK:"33895144",BLOCK_BAD_BLACK:"33895145"},Ob={CONTROL:"86748120",EXPERIMENT_BADGE_AFTER_TITLE:"86748121",EXPERIMENT_BADGE_AFTER_TEXT:"86748122",EXPERIMENT_BADGE_BENEATH_CREATIVE:"86748123"},Pb={CONTROL:"86726840",EXPERIMENT_BADGE_AFTER_TITLE:"86726841",
EXPERIMENT_BADGE_BENEATH_CREATIVE:"86726842"};var Qb={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function Rb(a){if(za)return m;a=a.google_page_location||a.google_page_url;if(!a)return m;a=a.toString();0==a.indexOf("http://")?a=a.substring(7,a.length):0==a.indexOf("https://")&&(a=a.substring(8,a.length));var b=a.indexOf("/");-1==b&&(b=a.length);a=a.substring(0,b);a=a.split(".");b=m;3<=a.length&&(b=a[a.length-3]in Qb);2<=a.length&&(b=b||a[a.length-2]in Qb);return b}
var Sb=function(a){var b=K();return"44901228"==b.b(1)?m:"44901229"==b.b(1)||Math.random()<ma?1==Math.floor(a/2)%2:m};var L=function(a,b,c){c||(c=Aa?"https":"http");return[c,"://",a,b].join("")};var M=function(a,b){this.I=a;this.m=b?b.m:[];this.B=b?b.B:m;this.M=b?b.M:"";this.C=b?b.C:0;this.r=b?b.r:"";this.f=b?b.f:[]};M.prototype.W=function(a,b){var c=this.I[b],d=this.m;this.I[b]=function(b){if(b&&0<b.length){var f=1<b.length?b[1].url:j;d.push([a,-1!=b[0].url.indexOf("&")?"document"in n?Ka(b[0].url):La(b[0].url):b[0].url,f])}c(b)}};var Tb=L(Ca(m),"/pagead/osd.js");M.prototype.U=function(){this.B||(ab(E()),Ya(Tb),this.B=i)};
M.prototype.s=function(a,b,c){var d=this.m;if(0<d.length)for(var e=a.document.getElementsByTagName("a"),f=0;f<e.length;f++)for(var g=0;g<d.length;g++)if(0<=e[f].href.indexOf(d[g][1])){var l=e[f].parentNode;if(d[g][2])for(var p=l,k=0;4>k;k++){if(0<=p.innerHTML.indexOf(d[g][2])){l=p;break}p=p.parentNode}b(l,d[g][0],c||0);d.splice(g,1);break}if(0<d.length&&a!=rb())try{this.s(a.parent,b,c)}catch(T){}};
M.prototype.A=function(a){this.s(this.I,a,1);for(var b=this.f.length,c=0;c<b;c++){var d=this.f[c];d.J&&a(d.J,d.ba,d.ea)}};M.prototype.setupOse=function(a){if(this.getOseId())return this.getOseId();var b=window.google_enable_ose,c;b===i?c=2:b!==m&&((c=hb([2],sa))||(c=hb([3],ta)));if(!c)return 0;this.C=c;this.r=""+(a||0);return this.getOseId()};M.prototype.getEid=function(){return""};M.prototype.getOseExpId=function(){return this.M};M.prototype.getOseId=function(){return this.C};
M.prototype.getCorrelator=function(){return this.r};M.prototype.z=function(){return this.m.length+this.f.length};M.prototype.registerAdBlock=function(a,b,c,d){"js"==c?this.W(a,"google_ad_request_done"):this.f.push(new Ub(a,b,c,d));this.U()};var Vb=function(){var a=E(),b=a.__google_ad_urls;if(!b)return a.__google_ad_urls=new M(a);try{b.getOseId()}catch(c){return a.__google_ad_urls=new M(a,b)}return b},Ub=function(a,b,c,d){this.ba=a;this.ea=b;this.J=d};s("Goog_AdSense_getAdAdapterInstance",Vb);
s("Goog_AdSense_OsdAdapter",M);s("Goog_AdSense_OsdAdapter.prototype.numBlocks",M.prototype.z);s("Goog_AdSense_OsdAdapter.prototype.getBlocks",M.prototype.A);s("Goog_AdSense_OsdAdapter.prototype.getEid",M.prototype.getEid);s("Goog_AdSense_OsdAdapter.prototype.getOseExpId",M.prototype.getOseExpId);s("Goog_AdSense_OsdAdapter.prototype.getOseId",M.prototype.getOseId);s("Goog_AdSense_OsdAdapter.prototype.getCorrelator",M.prototype.getCorrelator);s("Goog_AdSense_OsdAdapter.prototype.setupOse",M.prototype.setupOse);
s("Goog_AdSense_OsdAdapter.prototype.registerAdBlock",M.prototype.registerAdBlock);var Wb=function(a,b){this.x=a!==h?a:0;this.y=b!==h?b:0};var Xb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Yb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Zb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Yb.length;f++)c=Yb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var N,$b,ac,bc,cc,dc,ec,fc,gc=function(){return n.navigator?n.navigator.userAgent:j},hc=function(){cc=bc=ac=$b=N=m;var a;if(a=gc()){var b=n.navigator;N=0==a.indexOf("Opera");$b=!N&&-1!=a.indexOf("MSIE");bc=(ac=!N&&-1!=a.indexOf("WebKit"))&&-1!=a.indexOf("Mobile");cc=!N&&!ac&&"Gecko"==b.product}};hc();var ic=N,P=$b,jc=cc,Q=ac,kc=bc,lc=function(){var a=n.navigator;return a&&a.platform||""},mc=lc(),nc=function(){dc=-1!=mc.indexOf("Mac");ec=-1!=mc.indexOf("Win");fc=-1!=mc.indexOf("Linux")};nc();
var oc=dc,pc=ec,qc=fc,sc=function(){var a="",b;ic&&n.opera?(a=n.opera.version,a="function"==typeof a?a():a):(jc?b=/rv\:([^\);]+)(\)|;)/:P?b=/MSIE\s+([^\);]+)(\)|;)/:Q&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(gc()))?a[1]:""));return P&&(b=rc(),b>parseFloat(a))?""+b:a},rc=function(){var a=n.document;return a?a.documentMode:h},tc=sc(),uc={},vc=function(a){return uc[a]||(uc[a]=0<=Ra(tc,a))},wc={},xc=function(a){return wc[a]||(wc[a]=P&&!!document.documentMode&&document.documentMode>=a)};var yc,zc=!P||xc(9);!jc&&!P||P&&xc(9)||jc&&vc("1.9.1");P&&vc("9");var Ac=function(a){a=a.className;return q(a)&&a.match(/\S+/g)||[]},Cc=function(a,b){var c=Ac(a),d=Ab(arguments,1),e=c.length+d.length;Bc(c,d);a.className=c.join(" ");return c.length==e},Bc=function(a,b){for(var c=0;c<b.length;c++)0<=xb(a,b[c])||a.push(b[c])};var Dc=function(a){return a?new R(S(a)):yc||(yc=new R)},Ec=function(a){return q(a)?document.getElementById(a):a},Fc=Ec,Hc=function(a,b){Xb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Gc?a.setAttribute(Gc[d],b):0==d.lastIndexOf("aria-",0)?a.setAttribute(d,b):a[d]=b})},Gc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",
type:"type"},Ic=function(a){a=a.document;a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new u(a.clientWidth,a.clientHeight)},Jc=function(a){var b=!Q&&"CSS1Compat"==a.compatMode?a.documentElement:a.body,a=a.parentWindow||a.defaultView;return new Wb(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)},Lc=function(a,b,c){return Kc(document,arguments)},Kc=function(a,b){var c=b[0],d=b[1];if(!zc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',Ia(d.name),'"');if(d.type){c.push(' type="',
Ia(d.type),'"');var e={};Zb(e,d);d=e;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);d&&(q(d)?c.className=d:o(d)?Cc.apply(j,[c].concat(d)):Hc(c,d));2<b.length&&Mc(a,c,b,2);return c},Mc=function(a,b,c,d){function e(c){c&&b.appendChild(q(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];ca(f)&&!(da(f)&&0<f.nodeType)?yb(Nc(f)?zb(f):f,e):e(f)}},Oc=function(a){if(1!=a.nodeType)return m;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "STYLE":return m}return i},
Pc=function(a,b){a.appendChild(b)},Qc=function(a,b){Mc(S(a),a,arguments,1)},Rc=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):j},Sc=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},S=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},Nc=function(a){if(a&&"number"==typeof a.length){if(da(a))return"function"==
typeof a.item||"string"==typeof a.item;if("function"==ba(a))return"function"==typeof a.item}return m},R=function(a){this.k=a||n.document||document};R.prototype.createElement=function(a){return this.k.createElement(a)};R.prototype.createTextNode=function(a){return this.k.createTextNode(a)};R.prototype.R=function(){return"CSS1Compat"==this.k.compatMode};R.prototype.u=function(){return Jc(this.k)};R.prototype.appendChild=Pc;R.prototype.append=Qc;R.prototype.canHaveChildren=Oc;
R.prototype.removeNode=Rc;R.prototype.contains=Sc;var Tc=function(a,b){var c=b||w;a&&c.top!=c&&(c=c.top);try{return c.document&&!c.document.body?new u(-1,-1):Ic(c||window)}catch(d){return new u(-12245933,-12245933)}},Uc=function(a){if(a==a.top)return 0;var b=[];b.push(a.document.URL);a.name&&b.push(a.name);var c=i,a=Tc(!c,a);b.push(a.width.toString());b.push(a.height.toString());return jb(b.join(""))};var Vc=function(){var a="";if(document.documentMode){var b=document.createElement("IFRAME");b.frameBorder=0;b.style.height=0;b.style.width=0;b.style.position="absolute";if(document.body){document.body.appendChild(b);try{var c=b.contentWindow.document;c.open();c.write("<!DOCTYPE html>");c.close();a+=c.documentMode}catch(d){}document.body.removeChild(b)}}return a};var Wc=function(a){this.c=a;a.google_iframe_oncopy||(a.google_iframe_oncopy={handlers:{},log:[],shouldLog:0.01>Math.random()?i:m});this.H=a.google_iframe_oncopy;a.setTimeout(r(this.X,this),3E4)};Ia("var i=this.id,s=window.google_iframe_oncopy,H=s&&s.handlers,h=H&&H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&&d&&(!d.body||!d.body.firstChild)){if(h.call){i+='.call';setTimeout(h,0)}else if(h.match){i+='.nav';w.location.replace(h)}s.log&&s.log.push(i)}");
Wc.prototype.set=function(a,b){this.H.handlers[a]=b;this.c.addEventListener&&this.c.addEventListener("load",r(this.O,this,a),m)};Wc.prototype.O=function(a){var a=this.c.document.getElementById(a),b=a.contentWindow.document;if(a.onload&&b&&(!b.body||!b.body.firstChild))a.onload()};
Wc.prototype.X=function(){if(this.H.shouldLog){var a=this.H.log,b=this.c.document;a.length&&(b=["/pagead/gen_204?id=iframecopy&log=",y(a.join("-")),"&url=",y(b.URL.substring(0,512)),"&ref=",y(b.referrer.substring(0,512))].join(""),a.length=0,bb(this.c,L(Ba(),b)))}};var Xc=function(a){var a=a.webkitVisibilityState||a.mozVisibilityState||"",b={visible:1,hidden:2,prerender:3,preview:4};return b[a]||0};var Yc=function(a,b){var c=S(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,j))?c[b]||c.getPropertyValue(b)||"":""},U=function(a,b){return Yc(a,b)||(a.currentStyle?a.currentStyle[b]:j)||a.style&&a.style[b]},Zc=function(a){a=a?S(a):document;return P&&!xc(9)&&!Dc(a).R()?a.body:a.documentElement},$c=function(a){if(kc&&Q){var b=a.ownerDocument.defaultView;if(b!=b.top)return m}return!!a.getBoundingClientRect},ad=function(a){var b=a.getBoundingClientRect();
P&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b},bd=function(a){if(P&&!xc(8))return a.offsetParent;for(var b=S(a),c=U(a,"position"),d="fixed"==c||"absolute"==c,a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=U(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return j},cd=function(a){var b,
c=S(a),d=U(a,"position"),e=jc&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new Wb(0,0),g=Zc(c);if(a==g)return f;if($c(a))b=ad(a),a=Dc(c).u(),f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(g),f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(Q&&"fixed"==U(b,"position")){f.x+=c.body.scrollLeft;
f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(ic||Q&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=bd(b))&&b!=c.body&&b!=g;)if(f.x-=b.scrollLeft,!ic||"TR"!=b.tagName)f.y-=b.scrollTop}return f},ed=function(a,b){var c=new Wb(0,0),d=S(a)?S(a).parentWindow||S(a).defaultView:window,e=a;do{var f=d==b?cd(e):dd(e);c.x+=f.x;c.y+=f.y}while(d&&d!=b&&(e=d.frameElement)&&(d=d.parent));return c},dd=function(a){var b=new Wb;if(1==a.nodeType)if($c(a))a=ad(a),b.x=a.left,b.y=a.top;else{var c=Dc(a).u(),
a=cd(a);b.x=a.x-c.x;b.y=a.y-c.y}else{var c="function"==ba(a.getBrowserEvent),d=a;a.targetTouches?d=a.targetTouches[0]:c&&a.getBrowserEvent().targetTouches&&(d=a.getBrowserEvent().targetTouches[0]);b.x=d.clientX;b.y=d.clientY}return b},fd=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;b=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return b},gd=function(a){var b=S(a),c="";if(b.body.createTextRange){b=
b.body.createTextRange();b.moveToElementText(a);try{c=b.queryCommandValue("FontName")}catch(d){c=""}}c||(c=U(a,"fontFamily"));a=c.split(",");1<a.length&&(c=a[0]);return Ma(c,"\"'")},hd=/[^\d]+$/,id=function(a){return(a=a.match(hd))&&a[0]||j},jd={cm:1,"in":1,mm:1,pc:1,pt:1},kd={em:1,ex:1},ld=function(a){var b=U(a,"fontSize"),c=id(b);if(b&&"px"==c)return parseInt(b,10);if(P){if(c in jd)return fd(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&c in kd)return a=a.parentNode,c=U(a,"fontSize"),
fd(a,b==c?"1em":b,"left","pixelLeft")}c=Lc("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});Pc(a,c);b=c.offsetHeight;Rc(c);return b};var md={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},nd={google_ad_block:"ad_block",google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",
google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_mtl:"mtl",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",
google_skip:"skip",google_tdsma:"tdsma",google_tfs:"tfs",google_tl:"tl"},od={google_only_pyv_ads:"pyv",google_only_userchoice_ads:"uc",google_scs:"scs",google_with_pyv_ads:"withpyv",google_previous_watch:"p_w",google_previous_searches:"p_s"};var pd=function(a){var b=2;try{a.top.document==a.document?b=0:lb(a.top)&&(b=1)}catch(c){}return b};function qd(a,b){try{return a.top.document==b}catch(c){}return m}function rd(a,b,c,d){c=c||a.google_ad_width;d=d||a.google_ad_height;if(qd(a,b))return m;var e=b.documentElement;if(c&&d){var f=1,g=1;a.innerHeight?(f=a.innerWidth,g=a.innerHeight):e&&e.clientHeight?(f=e.clientWidth,g=e.clientHeight):b.body&&(f=b.body.clientWidth,g=b.body.clientHeight);if(g>2*d||f>2*c)return m}return i}function sd(a,b){x(b,function(b,d){a["google_"+d]=b})}
var td=function(a){var b=a.location.href;if(a==a.top)return{url:b,isTopUrl:i};var c=m,d=a.document;d&&d.referrer&&(b=d.referrer,a.parent==a.top&&(c=i));return{url:b,isTopUrl:c}};function ud(a,b,c){var d=pd(E()),a=!!a.google_referrer_url,e=4;!b&&1==d?e=5:!b&&2==d?e=6:b&&1==d?e=7:b&&2==d&&(e=8);e+=5*a;c&&(e|=16);return""+e}function vd(a,b,c){a.page_url=!c?b.URL:b.referrer;a.page_location=j}function wd(a,b,c,d){a.page_url=b.google_page_url;a.page_location=(!d?c.URL:c.referrer)||"EMPTY"}
function xd(a,b){var c={},d=pb(window),d=td(d),e=rd(E(),b,a.google_ad_width,a.google_ad_height);c.iframing=ud(a,e,d.isTopUrl);a.google_page_url?wd(c,a,b,e):vd(c,b,e);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1E3:j;c.referrer_url=e?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}
function yd(a){for(var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));-1<c.indexOf("%");)try{c=decodeURIComponent(c)}catch(d){break}b.iframing=j;b.page_url=c;b.page_location=a.URL;b.last_modified_time=j;b.referrer_url=c;return b}function zd(a){var b=Ad(a,E().document);sd(a,b)}function Ad(a,b){var c;return c=a.google_page_url==j&&Bd[b.domain]?yd(b):xd(a,b)}var Bd={"ad.yieldmanager.com":i};var Cd=function(a,b,c){b=r(b,n,a);a=window.onerror;window.onerror=b;try{c()}catch(d){var c=d.toString(),e="";d.fileName&&(e=d.fileName);var f=-1;d.lineNumber&&(f=d.lineNumber);b=b(c,e,f);if(!b)throw d;}window.onerror=a};s("google_protectAndRun",Cd);
var Ed=function(a,b,c,d){if(0.01>Math.random()){var e=v,a=["/pagead/gen_204","?id=jserror","&jscb=",xa?1:0,"&jscd=",ya?1:0,"&context=",y(a),"&msg=",y(b),"&file=",y(c),"&line=",y(d.toString()),"&url=",y(e.URL.substring(0,512)),"&ref=",y(e.referrer.substring(0,512))];a.push(Dd());a=L(Ba(),a.join(""));bb(w,a)}return!za};s("google_handleError",Ed);
var V=function(a){Fd|=a},Fd=0,Dd=function(){var a=["&client=",y(w.google_ad_client),"&format=",y(w.google_ad_format),"&slotname=",y(w.google_ad_slot),"&output=",y(w.google_ad_output),"&ad_type=",y(w.google_ad_type)];return a.join("")};var Id=function(){window.google_ad_output==j&&(window.google_ad_output="html");if(z(window.google_ad_format)){var a=window.google_ad_format.match(/^(\d+)x(\d+)_.*/);a&&(window.google_ad_width=parseInt(a[1],10),window.google_ad_height=parseInt(a[2],10),window.google_ad_output="html")}window.google_ad_format=Gd(window.google_ad_format,""+window.google_ad_output,Number(window.google_ad_width),Number(window.google_ad_height),window.google_ad_slot,!!window.google_override_format);window.google_ad_client=
Hd(window.google_ad_format,window.google_ad_client);zd(window);window.google_flash_version==j&&(window.google_flash_version=fb());window.google_ad_section=window.google_ad_section||window.google_ad_region||"";window.google_country=window.google_country||window.google_gl||"";a=(new Date).getTime();o(window.google_color_bg)&&(window.google_color_bg=W(window.google_color_bg,a));o(window.google_color_text)&&(window.google_color_text=W(window.google_color_text,a));o(window.google_color_link)&&(window.google_color_link=
W(window.google_color_link,a));o(window.google_color_url)&&(window.google_color_url=W(window.google_color_url,a));o(window.google_color_border)&&(window.google_color_border=W(window.google_color_border,a));o(window.google_color_line)&&(window.google_color_line=W(window.google_color_line,a))},Jd=function(a){x(md,function(b,c){a[c]=j});x(nd,function(b,c){a[c]=j});x(od,function(b,c){a[c]=j});a.google_container_id=j;a.google_enable_async=j;a.google_eids=j;a.google_page_location=j;a.google_referrer_url=
j;a.google_show_ads_impl=j;a.google_ad_region=j;a.google_gl=j;a.google_iframe_name=j;a.google_loader_used=j},W=function(a,b){V(2);return a[b%a.length]},Hd=function(a,b){if(!b)return"";b=b.toLowerCase();return b=z(a)?Kd(b):Ld(b)},Ld=function(a){a&&"ca-"!=a.substring(0,3)&&(a="ca-"+a);return a},Kd=function(a){a&&"ca-aff-"!=a.substring(0,7)&&(a="ca-aff-"+a);return a},Gd=function(a,b,c,d,e,f){!a&&"html"==b&&(a=c+"x"+d);return a=(!a?0:!e||f)?a.toLowerCase():""};var X=navigator;
function Md(a,b,c,d,e){var f=Math.round((new Date).getTime()/1E3),g=window.google_analytics_domain_name,a="undefined"==typeof g?Nd("auto",a):Nd(g,a),l=-1<b.indexOf("__utma="+a+"."),g=-1<b.indexOf("__utmb="+a),p=-1<b.indexOf("__utmc="+a),k=Gb("google_persistent_state"),k=I(k,14)||J(k,14,{});l?(b=b.split("__utma="+a+".")[1].split(";")[0].split("."),g&&p?k.sid=b[3]+"":k.sid||(k.sid=f+""),k.vid=b[0]+"."+b[1],k.from_cookie=i):(k.sid||(k.sid=f+""),k.vid||(k.vid=(Math.round(2147483647*Math.random())^Od(b,
c,d,e)&2147483647)+"."+f),k.from_cookie=m);k.dh=a;k.hid||(k.hid=Math.round(2147483647*Math.random()));return k}function Od(a,b,c,d){var e=[X.appName,X.version,X.language?X.language:X.browserLanguage,X.platform,X.userAgent,X.javaEnabled()?1:0].join("");c?e+=c.width+"x"+c.height+c.colorDepth:window.java&&(c=java.awt.Toolkit.getDefaultToolkit().getScreenSize(),e+=c.screen.width+"x"+c.screen.height);e+=a;e+=d||"";for(a=e.length;0<b;)e+=b--^a++;return Pd(e)}
function Pd(a){var b=1,c=0,d;if(!(a==h||""==a)){b=0;for(d=a.length-1;0<=d;d--)c=a.charCodeAt(d),b=(b<<6&268435455)+c+(c<<14),c=b&266338304,b=0!=c?b^c>>21:b}return b}function Nd(a,b){if(!a||"none"==a)return 1;a=""+a;"auto"==a&&(a=b,"www."==a.substring(0,4)&&(a=a.substring(4,a.length)));return Pd(a.toLowerCase())};var Y=function(a,b,c,d,e,f){this.aa=a;this.F=e;this.K=f;this.i=+c;this.h=+d;this.j=[]};Y.prototype.collapse=function(){var a=this.w();a&&this.$()};Y.prototype.g=function(a){this.e(a,"zIndex","999999")};Y.prototype.N=function(a,b,c){this.e(a,"width",b+"px");this.e(a,"height",c+"px");this.g(a)};Y.prototype.v=function(){var a=[],b=this.w();if(!b)return a;a.push(b);this.F&&this.K&&a.push(this.F.document.getElementById(this.K));return a};
Y.prototype.expand=function(a,b,c){var d=this.v();if(!(0>=d.length)){for(var e=0,f=d.length;e<f;++e)this.N(d[e],a,b);d=d[d.length-1];a>this.i&&(0==c||3==c)&&this.e(d,"left","-"+(a-this.i)+"px");b>this.h&&(1==c||0==c)&&this.e(d,"top","-"+(b-this.h)+"px");a=d.parentNode;b=a.parentNode;"ins"==a.nodeName.toLowerCase()&&(this.g(a),this.g(b));for(a=b.parentNode;a&&a.style&&"body"!=a.nodeName.toLowerCase();a=a.parentNode)"visible"!=a.style.overflow&&this.e(a,"overflow","visible")}};
Y.prototype.L=function(a,b){var c=this.v(),c=c[c.length-1],c=dd(c),d=this.F||window,d=Ic(d||window),e=a-this.i,f=b-this.h,g=c.y,f=f>g,l=d.height-(c.y+this.h),g=f||l>=g,f=c.x,e=e>f,c=d.width-(c.x+this.i),c=e||c>=f,d=2;g&&!c?d=3:!g&&c?d=1:!g&&!c&&(d=0);return d};Y.prototype.w=function(){this.Q||(this.Q=v.getElementById(this.aa));return this.Q};Y.prototype.e=function(a,b,c){this.j.push(new Qd(a,b,c))};Y.prototype.$=function(){for(var a=0,b=this.j.length;a<b;a++)this.j[a].undo();this.j.length=0};
var Qd=function(a,b,c){this.V=a;this.ca=b;this.da=a.style[b];this.V.style[b]=c};Qd.prototype.undo=function(){this.V.style[this.ca]=this.da};var Rd=function(a,b){var c=a.L(b.width,b.height);a.expand(b.width,b.height,c);return{width:b.width,height:b.height,direction:c}},Sd=function(a){a.collapse();return{}},Td=function(a,b){var c={},d=new Y(b.id,"",b.width,b.height,b.topMostFriendlyWindow,b.friendlyIframeId);c.expand=ga(Rd,d);c.collapse=ga(Sd,d);d={};iframes.open(a,b,d,c)},Ud=function(){iframes.setHandler("expandable",{onOpen:function(a){var b=a.getOpenParams(),c=b.container,d=b.width,e=b.height,f=b.id,g=f+"_anchor";if(b.friendlyIframeId)c=
document.createElement("div"),document.body.appendChild(c);else{var l=mb(g,d,e,"");c?(c.innerHTML=l,c=c.firstChild.firstChild):(document.write(l),c=document.getElementById(g))}return a=a.openInto(c,{id:f,width:d,height:e,style:b.cssStyle})},onReady:function(){},onClose:function(){}})};var Vd=(new Date).getTime();var Wd=function(a){var b="google_unique_id";a[b]?++a[b]:a[b]=1;return a[b]},Z=function(a){var b="google_unique_id",a=a[b];return"number"==typeof a?a:0},Xd=function(){var a=Nb;window.google_loader_experiment&&(a={async_bad_black:a.ASWIFT_BAD_BLACK,block_bad_black:a.BLOCK_BAD_BLACK},(a=a[window.google_loader_experiment])&&K().a([a],1,3))},Yd=function(){var a=window;((B?1==Z(a):!Z(a))||window.google_loader_experiment&&"none"!=window.google_loader_experiment&&"launch"!=window.google_loader_experiment)&&
Xd()},Zd=function(a){return a.google_slot_list&&a.google_slot_list.join?a.google_slot_list.join(",").slice(-100):""};var $=Ca(m),$d={};function ae(a,b){a&&""!=a&&($d[b]=1==b?$d[b]?$d[b]+(","+a):a:a)}function be(){var a=[];x($d,function(b){a.push(b)});return a.join(",")}function ce(a,b){if(o(a))for(var c=0;c<a.length;c++)q(a[c])&&ae(a[c],b)}var de=m;
function ee(a,b,c){var d="script";if(B?1==Z(a):!Z(a))K().a(["30143102","30143103"],qa,5),K().a(["33895250","33895251"],ra,7);de=fe(a,b);de||(a.google_allow_expandable_ads=m);var a=!ge(),e=Ob;if(de&&a){K().a(["30143205","30143206"],0,5);"undefined"!=typeof window.iframes&&V(8);K().a(["33895220","33895222","33895224","33895225"],na,5);var f=[e.CONTROL,e.EXPERIMENT_BADGE_AFTER_TITLE,e.EXPERIMENT_BADGE_AFTER_TEXT,e.EXPERIMENT_BADGE_BENEATH_CREATIVE];K().a(f,oa,5);var f=Pb,g=[f.CONTROL,f.EXPERIMENT_BADGE_AFTER_TITLE,
f.EXPERIMENT_BADGE_BENEATH_CREATIVE];K().a(g,pa,5);g=K().b(5);"33895222"==g||"33895224"==g||"33895225"==g||g==e.CONTROL||g==e.EXPERIMENT_BADGE_AFTER_TITLE||g==e.EXPERIMENT_BADGE_AFTER_TEXT||g==e.EXPERIMENT_BADGE_BENEATH_CREATIVE||g==f.CONTROL||g==f.EXPERIMENT_BADGE_AFTER_TITLE||g==f.EXPERIMENT_BADGE_BENEATH_CREATIVE?b.write("<"+d+' src="https://web.archive.org/web/20120613233705/https://ssl.gstatic.com/gb/js/gcm_01fa0dcbd17f41ae40e2e164313785ce.js"></'+d+">"):"33895223"==g?b.write("<"+d+' src="'+L($,"/pagead/js/gcm_01fa0dcbd17f41ae40e2e164313785ce.js")+'"></'+d+">"):"33895221"==
g?b.write("<"+d+' src="'+L($,"/pagead/js/expansion_embed_exp.js")+'"></'+d+">"):b.write("<"+d+' src="'+L($,"/pagead/expansion_embed.js")+'"></'+d+">");("33895224"==g||"33895225"==g)&&b.write("<"+d+' src="'+L($,"/pagead/expansion_embed.js")+'"></'+d+">")}(c=a||c)&&cb("msie")&&!window.opera?b.write("<"+d+' src="'+L($,"/pagead/render_ads.js")+'"></'+d+">"):b.write("<"+d+'>google_protectAndRun("ads_core.google_render_ad", google_handleError, google_render_ad);</'+d+">")}
function he(a){return a!=j?'"'+a+'"':'""'}var ie=function(a,b){if("about:blank"===b)return b;var c=b.slice(-1),d="?"==c||"#"==c?"":"&",e=[b],c=function(a,b){if(a||0===a||a===m)"boolean"==typeof a&&(a=a?1:0),Xa(e,d,b,"=",y(a)),d="&"};x(a,c);return e.join("")},je=function(){var a=P&&vc("8"),b=jc&&vc("1.8.1"),c=Q&&vc("525");return pc&&(a||b||c)||oc&&(c||b)||qc&&(c||b)?i:m};function ge(){return"object"==typeof ExpandableAdSlotFactory&&"function"==typeof ExpandableAdSlotFactory.createIframe}
function fe(a,b){var c=a.google_ad_width,d=a.google_ad_height,e=E();try{if(a.google_allow_expandable_ads===m||!b.body||"html"!=a.google_ad_output||rd(e,e.document,c,d)||!ke(a)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!je()||b.domain!=a.location.hostname)return m}catch(f){return m}return i}function ke(a){var b=a.google_ad_format;return z(b)||gb(a)&&"468x15_0ads_al"!=b?m:i}var le=function(){var a=Vb(),b=Gb();return a.setupOse(I(b,7))};
function me(a,b,c,d){B||Wd(a);var e=Z(a),c=ie({ifi:e},c),c=c.substring(0,1991),c=c.replace(/%\w?$/,""),f="script",g="google_ads_frame"+e,l=K().b(5),p=j;if(("js"==a.google_ad_output||"json_html"==a.google_ad_output)&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+he(ne(c))+"></"+f+">");else if("html"==a.google_ad_output){var f=de?c.replace(/&ea=[^&]*/,"")+"&ea=0":c,f=['<iframe id="',g,'" name="',g,'" width=',he(""+a.google_ad_width)," height=",
he(""+a.google_ad_height),' frameborder="0" src=',he(ne(f)),' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>'].join(""),k=Ob,T=Pb,d=a.google_container_id||d||j;"object"==typeof iframes&&"function"==typeof iframes.open&&("33895222"==l||"33895223"==l||"33895225"==l||l==k.CONTROL||l==k.EXPERIMENT_BADGE_AFTER_TITLE||l==k.EXPERIMENT_BADGE_AFTER_TEXT||l==k.EXPERIMENT_BADGE_BENEATH_CREATIVE||l==T.CONTROL||l==T.EXPERIMENT_BADGE_AFTER_TITLE||l==T.EXPERIMENT_BADGE_BENEATH_CREATIVE)?
(Ud(),iframes.setVersionOverride("gcm_01fa0dcbd17f41ae40e2e164313785ce.js"),d={style:"expandable",id:g,rpcToken:"adsense_rpc_key",width:a.google_ad_width,height:a.google_ad_height,cssStyle:"left:0;position:absolute;top:0",topMostFriendlyWindow:E(),friendlyIframeId:a.google_async_iframe_id},Td(ne(c),d)):de&&ge()?a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe(g,ne(c),a.google_ad_width,a.google_ad_height,d,E(),a.google_async_iframe_id):a.google_container_id?oe(a.google_container_id,b,f):b.write(f);
p=document.getElementById(g);B&&pe(a.google_async_iframe_id,f);if(qe){if(3!=Xc(b))re("/pagead/ads?",p);else{var D=function(){re("/pagead/ads?",p);$a(v,"webkitvisibilitychange",D)};Za(b,"webkitvisibilitychange",D)}qe=m}}"30143103"==l&&(1==e&&!a.google_container_id)&&b.write('<iframe height=1 src="'+L($,"/pagead/s/iframes_api_loader.html")+'" style="position:absolute;visibility:hidden" width=1></iframe>');a=Vb();a.getOseId()&&a.registerAdBlock(c,1,""+(window.google_ad_output||""),p);return c}
var pe=function(a,b){var c="javascript:"+Qa(["<!DOCTYPE html><html><body>",b,"</body></html>"].join("")),d=E();(new Wc(d)).set(a,c)};function se(a){Jd(a)}
var ve=function(a,b){var c="44901217"==Mb().b(2);if(!te(c))return m;var d=!Rb(window)?Sb(Z(window))?ka("","googleads2.g.doubleclick.net"):ka("","googleads.g.doubleclick.net"):Ba(),c=ue(a);if(z(window.google_ad_format))return window.google_ad_url="about:blank",i;d=L(d,b+"");window.google_ad_url=ie(c,d);return i},qe=m,we=function(a){var b=K().b(9);return"html"===w.google_ad_output&&3==Xc(v)&&"373855200"===b?(qe=i,V(32),ve(a,"/pagead/gen_204?id=prerender")):
ve(a,"/pagead/ads?")},Ae=function(a){a.dt=Vd;B&&window.google_bpp&&(a.bpp=window.google_bpp);a.shv=wa();var b=!!window.google_test_1,c=!!window.google_test_2;b&&(a.tsi=c?"3":"2");a.jsv="/r20110914".replace("/","");window.google_loader_used&&(a.saldr=1);var b=Gb(),c=I(b,8),d=window.google_ad_section,e=window.google_ad_format,f=window.google_ad_slot;c[d]&&(z(e)||(a.prev_fmts=c[d]));var g=I(b,9);g[d]&&(a.prev_slotnames=g[d].toLowerCase());
e?z(e)||(c[d]=c[d]?c[d]+(","+e):e):f&&(g[d]=g[d]?g[d]+(","+f):f);a.correlator=I(b,7);if(window.google_ad_channel){c=I(b,10);d="";e=window.google_ad_channel.split(xe);for(f=0;f<e.length;f++)g=e[f],c[g]?d+=g+"+":c[g]=i;a.pv_ch=d}window.google_ad_host_channel&&(b=ye(window.google_ad_host_channel,I(b,11)),a.pv_h_ch=b);xa&&(a.jscb=1);ya&&(a.jscd=1);a.frm=window.google_iframing;a.adk=ze();b=E().document;b=Md(b.domain,b.cookie,window.history.length,window.screen,b.referrer);a.ga_vid=b.vid;a.ga_sid=b.sid;
a.ga_hid=b.hid;a.ga_fc=b.from_cookie;a.ga_wpids=window.google_analytics_uacct},Be=function(a){var b=E(),c=m,d=Tc(c,b.top);d&&(a.biw=d.width,a.bih=d.height);if(b.top!=b&&(b=Tc(c,b)))a.isw=b.width,a.ish=b.height},ze=function(){var a=[];Xa(a,w.google_ad_slot,w.google_ad_format,w.google_ad_type,w.google_ad_width,w.google_ad_height);var b=B?wb():Ta;b&&(b=kb(b))&&a.push(b);b=0;a&&(b=jb(a.join(":")));return b.toString()},Ce=function(a){var b=Uc(E());0!=b&&(a.ifk=b.toString())},De=function(a){var b=Vb();
(b=b.getOseId())&&(a.oid=b)};function ye(a,b){for(var c=a.split("|"),d=-1,e=[],f=0;f<c.length;f++){var g=c[f].split(xe);b[f]||(b[f]={});for(var l="",p=0;p<g.length;p++){var k=g[p];""!=k&&(b[f][k]?l+="+"+k:b[f][k]=i)}l=l.slice(1);e[f]=l;""!=l&&(d=f)}c="";if(-1<d){for(f=0;f<d;f++)c+=e[f]+"|";c+=e[d]}return c}function Ee(){var a=["44901228","44901229"];K().a(a,la,1);a=["44901218","44901217"];K().a(a,ua,2);"html"===w.google_ad_output&&3==Xc(v)&&(a=["373855201","373855200"],K().a(a,va,9))}
var Fe=function(){rb()!=E()&&V(4);Aa&&V(16)};function Ge(){Fe();if(B?1==Z(window):!Z(window))Ee(),le();var a=j,b="";(a=window.google_async_iframe_id)?a=E().document.getElementById(a):(b="google_temp_span",a=He(b));var c=we(a);a&&a.id==b&&Rc(a);c&&(me(window,document,window.google_ad_url),se(window));vb(window)}
var Ie=function(a){x(nd,function(b,c){a[b]=window[c]});x(md,function(b,c){a[b]=window[c]});x(od,function(b,c){a[b]=window[c]})},Je=function(a){o(window.google_eids)&&0!==window.google_eids.length&&V(64);ce(window.google_eids,1);a.eid=be();var b=Mb().P();0<a.eid.length&&0<b.length&&(a.eid+=",");a.eid+=b};function Ke(a,b,c,d){a=Ed(a,b,c,d);ee(window,document);return a}function Le(){Id()}
function Me(a){for(var b={},a=a.split("?"),a=a[a.length-1].split("&"),c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=1<d.length?window.decodeURIComponent?decodeURIComponent(d[1].replace(/\+/g," ")):unescape(d[1]):""}catch(e){}}return b}function Ne(){var a=window,b=Me(document.URL);b.google_ad_override&&(a.google_ad_override=b.google_ad_override,a.google_adtest="on")}
function oe(a,b,c){if(a&&(a=b.getElementById(a))&&c&&""!=c.length)a.style.visibility="visible",a.innerHTML=c}
var Oe=function(a,b,c){var d=a.indexOf(b);if(-1===d)return a;b=d+b.length;return a.substr(0,d)+c+a.substr(b)},re=function(a,b){var c=b.src,d=Oe(c,"/pagead/gen_204?id=prerender",a);d!==c&&(b.src=d)},Pe=function(a,b){b.dff=gd(a).toLowerCase();b.dfs=ld(a)},Qe=function(a,b){if("html"==w.google_ad_output)try{var c=ed(a,window.top);b.adx=Math.round(c.x);b.ady=Math.round(c.y)}catch(d){b.adx=-12245933,b.ady=-12245933}},Re=function(a){a.ref=window.google_referrer_url;a.loc=window.google_page_location;"33895251"==
K().b(7)&&(a.aasl=Zd(E()));var b=rb(),b=td(b);b.url!=a.url&&(b.url!=a.ref&&b.url!=a.loc)&&(a.top=b.url);a.docm=Vc()},te=function(a){var b=Gb(),c=I(b,8),d=I(b,9),e=window.google_ad_section;if(z(window.google_ad_format)){if(4<J(b,4,I(b,4)+1)&&!a)return m}else if(gb(window)){if(3<J(b,5,I(b,5)+1)&&!a)return m}else{var f=J(b,6,I(b,6)+1);if(window.google_num_slots_to_rotate){if(V(1),c[e]="",d[e]="",I(b,12)||J(b,12,(new Date).getTime()%window.google_num_slots_to_rotate+1),I(b,12)!=f)return m}else if(!a&&
6<f&&""==e)return m}return i},ue=function(a){var b={};Ie(b);Ae(b);ib(b);a&&(Pe(a,b),Qe(a,b));Be(b);Ce(b);Je(b);De(b);Re(b);b.fu=Fd;return b},He=function(a){var b=window.google_container_id,c=b&&Fc(b)||Fc(a);!c&&(!b&&a)&&(document.write("<span id="+a+"></span>"),c=Fc(a));return c},ne=function(a){var b=(new Date).getTime()-Vd;return ie({dtd:1E4>b?b:"M"},a)},xe=/[+, ]/;window.google_render_ad=Ge;function Se(){Ne();Yd();var a=window.google_start_time;"number"==typeof a&&(Vd=a,window.google_start_time=j);Cd("show_ads.google_init_globals",Ke,Le);ee(window,document)}Cd("show_ads.main",Ed,Se);})()

}

/*
     FILE ARCHIVED ON 23:37:05 Jun 13, 2012 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:16:27 Jun 16, 2026.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  capture_cache.get: 0.431
  load_resource: 201.804 (2)
  PetaboxLoader3.resolve: 91.799 (2)
  PetaboxLoader3.datanode: 70.65 (2)
*/